# -*- coding: utf-8 -*-
"""Soil_Nitrogen_Pipeline_v2.0

Automatically generated by Colab.

Original file is located at
*collab link*

# Soil Nitrogen Dynamics & Forecast Pipeline
**University of Nebraska-Lincoln — ENREEC Research**

This notebook provides a robust framework for integrating soil nitrogen data, remote sensing covariates (GEE), and greenhouse gas (GHG) fluxes into a Gaussian Process Regression (GPR) model to forecast soil N trajectories through 2030.

### Core Objectives:
1. **Data Fusion:** Combine field samples with Sentinel-2 vegetation indices (NDVI, EVI).
2. **Feature Selection:** Use Random Forest to identify primary drivers for NH4 vs NO3.
3. **Probabilistic Forecasting:** Use GPR with target-specific kernels to project 2030 levels with 95% confidence intervals.
4. **Treatment Analysis:** Compare Unfertilized, Fertilized, and Legume-integrated systems under grazed vs. non-grazed management.

## 1. Environmental Setup & Data Ingestion
We begin by installing necessary dependencies for spatial analysis and modeling, mounting Google Drive, and loading the master Nitrogen dataset. The dataset includes $NH_4^+$ and $NO_3^-$ concentrations across different treatments and depths.
"""

# Step 1: Install Dependencies
!pip install openpyxl scikit-learn matplotlib seaborn -q

# Step 2: Import Libraries and Mount Drive
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern, WhiteKernel
from sklearn.preprocessing import LabelEncoder
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive', force_remount=True)
print('Libraries loaded successfully.')

# Step 3: Load Master Dataset
FILE_PATH = 'path/to/data'   # set to your own data directory
df = pd.read_csv(FILE_PATH)
print(f'Loaded: {df.shape[0]} rows')
display(df.head())

"""## 2. Data Validation & Preprocessing
This section audits the dataset for missing values, ensures consistency in column naming, and maps treatment codes to descriptive labels (e.g., 'Fertilized Triticale').
"""

# Step 4: Data Quality Audit
print('=== Missing values ===')
print(df[['nh4_mg_kg','no3_mg_kg']].isnull().sum())

print('\n=== Sample counts by year × treatment × grazing ===')
print(df.groupby(['year','treatment_code','grazing'])['sample_id'].count())

# Step 5: Clean Treatment Labels
TREATMENT_LABELS = {1: 'Unfertilized Triticale', 2: 'Fertilized Triticale', 3: 'Triticale w/ Legume'}
df['treatment_name_clean'] = df['treatment_code'].map(TREATMENT_LABELS)
print('Treatment labels mapped.')

"""## 3. Exploratory Data Analysis (EDA)
We visualize the raw trajectories from 2019–2023 to identify baseline trends and variance across treatments and soil depths (0-10cm and 10-20cm).
"""

import matplotlib.pyplot as plt

# Step 6: Initial Trend Visualization
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for ax, var, label in zip(axes, ['nh4_mg_kg', 'no3_mg_kg'], ['NH₄⁺ (mg/kg)', 'NO₃⁻ (mg/kg)']):
    for trt, grp in df.groupby('treatment_name_clean'):
        yearly = grp.groupby('year')[var].mean()
        ax.plot(yearly.index, yearly.values, marker='o', label=trt)
    ax.set_title(label)
    ax.set_xlabel('Year')
    ax.set_ylabel(label)
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

plt.suptitle('Mean NH₄⁺ and NO₃⁻ by Treatment (2019–2023)', fontweight='bold')
plt.tight_layout()
plt.show()

# Step 7: Soil Depth Analysis
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

for i, (var, label) in enumerate([('nh4_mg_kg','NH₄⁺'), ('no3_mg_kg','NO₃⁻')]):
    for j, depth in enumerate(['0-10', '10-20']):
        ax = axes[i][j]
        sub = df[df['depth_cm'] == depth]
        sns.boxplot(data=sub, x='year', y=var, hue='treatment_name_clean', ax=ax, palette='Set2')
        ax.set_title(f'{label} — {depth} cm')
        ax.set_xlabel('Year')
        ax.set_ylabel(f'{label} (mg/kg)')
        ax.legend(fontsize=7, title='Treatment')
        ax.grid(alpha=0.3)

plt.tight_layout()
plt.show()

"""## 4. Aggregate to Plot-Level Means (GPR Input)"""

# Step 8: Aggregate to Plot-Level Means
gpr_input = (
    df.groupby(['year','plot_id','treatment_code',
                'treatment_name_clean','time_point','depth_cm', 'grazing'],
               as_index=False)
    .agg(
        nh4_mean=('nh4_mg_kg', 'mean'),
        nh4_std=('nh4_mg_kg', 'std'),
        no3_mean=('no3_mg_kg', 'mean'),
        no3_std=('no3_mg_kg', 'std'),
        n_reps=('nh4_mg_kg', 'count')
    )
)

print(f'GPR input shape: {gpr_input.shape}')
display(gpr_input.head())

import pandas as pd
import numpy as np

# Step 9: Statistical Thresholding and Outlier Identification
# Calculate percentiles to define robust boundaries for the GPR
percentiles = gpr_input_gee[['nh4_mean', 'no3_mean']].quantile([0.90, 0.95, 0.99])
print("Statistical Thresholds for Outlier Handling:")
display(percentiles)

# Defining caps to prevent model instability
nh4_cap = percentiles.loc[0.90, 'nh4_mean']
no3_cap = percentiles.loc[0.90, 'no3_mean']

"""## 4. GPR Modeling Framework (Core Logic)
We define the Gaussian Process Regression function. Key features include:
* **Log-Transformation:** Prevents the model from predicting impossible negative nitrogen concentrations.
* **Outlier Capping:** Uses the 90th percentile to prevent extreme spikes from over-inflating uncertainty bands.
* **Standard Scaling:** Normalizes inputs to improve kernel optimization convergence.
"""

### Step 10 & 15 Consolidated: The Unified GPR Engine
We have consolidated the GPR logic into a single, robust function `run_gpr_refined`. This function handles:
1. **Dynamic Feature Selection:** Automatically chooses NDVI for $NO_3^-$ and EVI for $NH_4^+$.
2. **Management Factor:** Handles 'Grazed' vs 'Non-Grazed' status.
3. **Stability:** Uses log-scaling and improved kernel bounds to prevent convergence crashes during reruns.

"""## 6. Final Audited Execution
We now execute the consolidated GPR engine. This generates the 2030 forecasts using target-specific covariates (NDVI/EVI) while accounting for grazing management and soil depth. The model uses log-transformations and capped percentiles to ensure the most robust predictions possible.
"""

### Step 11: Final Audited Execution
This cell executes the model for the entire experimental design. By using the consolidated engine, we ensure that every rerun follows the same logic for outlier capping and feature scaling, preventing inconsistencies between the 'baseline' and 'refined' versions.

"""### Summary of Current Progress
- **Robust Data-Fusion:** Integrated field data with Sentinel-2 NDVI/EVI covariates.
- **Feature Selection:** Confirmed NDVI as a primary driver for $NO_3^-$ and EVI for $NH_4^+$.
- **Audited Forecasting:** GPR models now include management status (Grazing) and are optimized for convergence.
- **Next Steps:** Integrate GHG flux data once uploaded and incorporate microbial FAME data for mechanistic insights.
"""

### Step 12: Google Earth Engine Covariate Extraction
We interface with Sentinel-2 satellite data to extract NDVI and EVI values for each plot, providing high-resolution vegetation indicators for the GPR model.

# Step 13: Data Fusion
# Merge GEE covariates into gpr_input
gpr_input_gee = gpr_input.merge(
    gee_df[['plot_id', 'year', 'time_point', 'treatment_code', 'ndvi', 'evi']],
    on=['plot_id', 'year', 'time_point', 'treatment_code'],
    how='left'
)
print('Data fusion complete.')

"""## 5c. Integrate GHG Flux Data
This step imports the greenhouse gas flux data and merges it with our soil N and GEE covariate dataset to provide a mechanistic indicator of microbial/gaseous activity.
"""

import os

# Helper to find the correct GHG file path
def find_ghg_file(search_dir='/content/drive/MyDrive/ENREEC/'):
    print(f"Searching for GHG files in {search_dir}...")
    matches = []
    for root, dirs, files in os.walk(search_dir):
        for file in files:
            if 'ghg' in file.lower() and file.endswith('.csv'):
                matches.append(os.path.join(root, file))
    return matches

found_files = find_ghg_file()

if found_files:
    GHG_FILE_PATH = found_files[0]
    print(f"Found potential GHG file: {GHG_FILE_PATH}")

    try:
        ghg_df = pd.read_csv(GHG_FILE_PATH)
        # Aggregate GHG data to plot-level yearly means
        # Standardizing column names to lowercase for robust merging
        ghg_df.columns = [c.lower() for c in ghg_df.columns]

        ghg_agg = ghg_df.groupby(['year', 'plot_id', 'treatment_code'], as_index=False).agg({
            'co2_flux': 'mean',
            'n2o_flux': 'mean',
            'ch4_flux': 'mean'
        })

        # Merge into the master GPR input dataframe
        gpr_input_gee = gpr_input_gee.merge(
            ghg_agg,
            on=['year', 'plot_id', 'treatment_code'],
            how='left'
        )
        print('GHG flux data integrated successfully.')
        display(gpr_input_gee[['year', 'plot_id', 'co2_flux', 'n2o_flux']].head())
    except Exception as e:
        print(f'Error processing {GHG_FILE_PATH}: {e}')
else:
    print('No GHG CSV files found. Please check the file name and location in Google Drive.')

"""### 5d. GHG Data Upload & Integration
Use the cell below to upload your `GHG_flux_data.csv` directly to the Colab runtime if it is not yet in your Google Drive.
"""

from google.colab import files
import io

print("Please upload your GHG flux CSV file:")
uploaded = files.upload()

if uploaded:
    filename = list(uploaded.keys())[0]
    ghg_df = pd.read_csv(io.BytesIO(uploaded[filename]))

    # Standardize columns
    ghg_df.columns = [c.lower() for c in ghg_df.columns]

    # Aggregate and merge
    ghg_agg = ghg_df.groupby(['year', 'plot_id', 'treatment_code'], as_index=False).agg({
        'co2_flux': 'mean',
        'n2o_flux': 'mean',
        'ch4_flux': 'mean'
    })

    gpr_input_gee = gpr_input_gee.merge(
        ghg_agg,
        on=['year', 'plot_id', 'treatment_code'],
        how='left'
    )
    print(f"\nSuccessfully integrated {filename} into the GPR dataset.")
    display(gpr_input_gee.head())
else:
    print("No file uploaded. Re-run this cell when your GHG data is ready.")

"""## 5. Feature-Selected GPR & Forecasts
In this stage, we integrate the **Google Earth Engine (GEE)** covariates. Based on Random Forest importance, we use **NDVI** as the primary covariate for $NO_3^-$ and **EVI** for $NH_4^+$. We generate separate forecasts for **Grazed** vs **Non-Grazed** plots to reflect management impacts.
"""

from sklearn.preprocessing import StandardScaler
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern, WhiteKernel
import numpy as np

def run_gpr_refined(data, target_col, treatment_code, depth='0-10', grazing_status='No'):
    """
    Audited GPR Engine: Handles year + vegetation covariates with robust outlier management.
    """
    covariate = 'ndvi' if 'no3' in target_col else 'evi'

    # Filtering subset
    sub = data[
        (data['treatment_code'] == treatment_code) &
        (data['depth_cm'] == depth) &
        (data['grazing'] == grazing_status)
    ].dropna(subset=[target_col, covariate])

    if sub.empty or len(sub) < 3:
        return None, None, None, None, None, None

    X_train = sub[['year', covariate]].values.astype(float)

    # Calculate threshold from full dataset column to ensure stability
    global_target = data[target_col].dropna()
    threshold = global_target.quantile(0.90) if not global_target.empty else None

    # Perform robust clipping
    y_raw = sub[target_col].values
    if threshold is not None:
        y_raw = np.clip(y_raw, a_min=None, a_max=threshold)

    y_train = np.log1p(y_raw)

    scaler_X = StandardScaler()
    X_train_scaled = scaler_X.fit_transform(X_train)

    kernel = (Matern(nu=1.5, length_scale_bounds=(1e-5, 1e5)) *
              Matern(nu=1.5, length_scale_bounds=(1e-5, 1e5))) + \
             WhiteKernel(noise_level=0.1, noise_level_bounds=(1e-7, 1e2))

    gpr = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=20, normalize_y=True, random_state=42)
    gpr.fit(X_train_scaled, y_train)

    X_pred_years = np.arange(2019, 2031).reshape(-1, 1)
    mean_cov = sub[covariate].mean()
    X_pred = np.hstack([X_pred_years, np.full((len(X_pred_years), 1), mean_cov)])

    X_pred_scaled = scaler_X.transform(X_pred)
    y_mean_log, y_std_log = gpr.predict(X_pred_scaled, return_std=True)

    return (
        X_pred_years.flatten(),
        np.expm1(y_mean_log),
        np.expm1(y_mean_log - 2 * y_std_log),
        np.expm1(y_mean_log + 2 * y_std_log),
        sub['year'].values,
        sub[target_col].values
    )

"""## 6b. Forecast Plots with GEE Covariates — 2019 to 2030"""

TREATMENTS = [1, 2, 3]
TREATMENT_LABELS = {1: 'Unfertilized Triticale', 2: 'Fertilized Triticale', 3: 'Triticale w/ Legume'}
COLORS = {1: '#2196F3', 2: '#4CAF50', 3: '#FF9800'}
GRAZING_STATUSES = ['No', 'Yes']

for grazing_status in GRAZING_STATUSES:
    for target, label in [('nh4_mean', 'NH₄⁺'), ('no3_mean', 'NO₃⁻')]:
        fig, axes = plt.subplots(1, 3, figsize=(16, 5), sharey=True)
        best_cov = 'EVI' if 'nh4' in target else 'NDVI'

        for i, trt in enumerate(TREATMENTS):
            ax = axes[i]
            color = COLORS[trt]

            # Execute refined GPR
            res = run_gpr_refined(
                gpr_input_gee, target, trt, depth='0-10', grazing_status=grazing_status
            )

            # Skip plotting if the model returned None due to insufficient data
            if res[0] is None:
                ax.text(0.5, 0.5, 'Insufficient Data', ha='center', va='center', color='gray')
                ax.set_title(f'{TREATMENT_LABELS[trt]} (N/A)', fontsize=9)
                continue

            X_pred, y_mean, y_lower, y_upper, X_obs, y_obs = res

            ax.fill_between(X_pred, np.maximum(y_lower, 0), y_upper, alpha=0.15, color=color, label='95% CI')
            ax.plot(X_pred, y_mean, color=color, lw=2, label='Refined GPR')
            ax.scatter(X_obs, y_obs, color=color, s=50, edgecolors='white', zorder=5)
            ax.axvline(2023.5, color='gray', linestyle='--', alpha=0.5)
            ax.set_title(f'{TREATMENT_LABELS[trt]}', fontsize=10)
            ax.set_xlim(2018.5, 2030.5)
            ax.set_ylim(bottom=0)
            ax.grid(alpha=0.2)

        plt.suptitle(f'{label} Forecast (0–10 cm, {grazing_status} Grazing) - Feature-Selected ({best_cov})', fontweight='bold')
        plt.tight_layout()
        plt.show()

"""## 7. Random Forest Feature Selection
In this step, we use a Random Forest Regressor to rank the importance of our environmental covariates (NDVI, EVI) in predicting soil nitrogen levels. This addresses the 'robust data-fusion pipeline' objective by quantifying feature relevance.
"""

from sklearn.ensemble import RandomForestRegressor

# Step 14: Feature Importance Audit
def audit_feature_importance(df, target_col):
    # Prepare features: Year + GEE Indices
    features = ['year', 'ndvi', 'evi']
    sub = df.dropna(subset=[target_col] + features)

    X = sub[features]
    y = sub[target_col]

    rf = RandomForestRegressor(n_estimators=100, random_state=42)
    rf.fit(X, y)

    importance = pd.Series(rf.feature_importances_, index=features).sort_values(ascending=False)
    return importance

print("Feature Importance for Ammonium (NH4):")
nh4_importance = audit_feature_importance(gpr_input_gee, 'nh4_mean')
display(nh4_importance)

print("\nFeature Importance for Nitrate (NO3):")
no3_importance = audit_feature_importance(gpr_input_gee, 'no3_mean')
display(no3_importance)