# -*- coding: utf-8 -*-
"""Soil_Nitrogen_Pipeline_v2.1.ipynb

Automatically generated by Colab.

Original file is located at
    *google collab file*

# Soil Nitrogen Dynamics Pipeline v2.1 with SPEI
**Airori & Mamo — University of Nebraska-Lincoln**

**Pipeline stages:**
1. Setup & load data
2. Validate & summarize
3. Exploratory visualization
4. GEE covariate extraction (NDVI, EVI)
5. Feature engineering (grazing, treatment, depth, GEE)
6. Random Forest feature selection (SPEI Extracted)
7. GPR modeling using top RF features
8. Forecast to 2030

## 1. Setup & Load Data
"""

!pip install openpyxl scikit-learn matplotlib seaborn earthengine-api -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.ensemble import RandomForestRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern, WhiteKernel
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.inspection import permutation_importance
import ee
from google.colab import drive

drive.mount('/content/drive')
print('Libraries loaded successfully.')

# ── EDIT THIS PATH ──────────────────────────────────────────────────────────
FILE_PATH = 'path/to/data'   # set to your own data directory
# ────────────────────────────────────────────────────────────────────────────

df = pd.read_csv(FILE_PATH)

# Standardize grazing column
df['grazing'] = df['grazing'].str.strip().str.capitalize()
df['grazing_binary'] = (df['grazing'] == 'Yes').astype(int)

# Depth as numeric (use top value: 0-10 → 5, 10-20 → 15)
df['depth_numeric'] = df['depth_cm'].map({'0-10': 5, '10-20': 15})

print(f'Loaded: {df.shape[0]} rows x {df.shape[1]} columns')
print(f'Years: {sorted(df["year"].unique())}')
print(f'Treatments: {df["treatment_code"].unique()}')
print(f'Grazing values: {df["grazing"].unique()}')
df.head()

"""## 2. Validate & Summarize"""

print('=== Missing values ===')
print(df[['nh4_mg_kg','no3_mg_kg']].isnull().sum())

print('\n=== Sample counts by year x treatment x grazing ===')
print(df.groupby(['year','treatment_code','grazing'])['sample_id'].count().to_string())

print('\n=== NH4+ summary stats ===')
print(df.groupby('treatment_code')['nh4_mg_kg'].describe().round(2))

print('\n=== NO3- summary stats ===')
print(df.groupby('treatment_code')['no3_mg_kg'].describe().round(2))

"""## 3. Exploratory Visualization"""

TREATMENT_LABELS = {
    1: 'Unfertilized Triticale',
    2: 'Fertilized Triticale',
    3: 'Triticale w/ Legume'
}
COLORS = {1: '#2196F3', 2: '#4CAF50', 3: '#FF9800'}
df['treatment_label'] = df['treatment_code'].map(TREATMENT_LABELS)

# Mean trajectories by treatment
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
for ax, var, label in zip(axes,
                           ['nh4_mg_kg','no3_mg_kg'],
                           ['NH\u2084\u207a (mg/kg)','NO\u2083\u207b (mg/kg)']):
    for trt_code, trt_label in TREATMENT_LABELS.items():
        for grazing_val, ls in [('Yes','--'), ('No','-')]:
            sub = df[(df['treatment_code']==trt_code) & (df['grazing']==grazing_val)]
            yearly = sub.groupby('year')[var].mean()
            ax.plot(yearly.index, yearly.values,
                    color=COLORS[trt_code], linestyle=ls,
                    marker='o', linewidth=1.5,
                    label=f'{trt_label} ({grazing_val})')
    ax.set_title(label)
    ax.set_xlabel('Year')
    ax.set_ylabel(label)
    ax.legend(fontsize=7, ncol=2)
    ax.grid(alpha=0.3)

plt.suptitle('Mean N Trajectories by Treatment and Grazing (2019-2023)', fontweight='bold')
plt.tight_layout()
plt.savefig('N_trajectories_grazing.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: N_trajectories_grazing.png')

# Boxplots split by grazing and depth
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
for i, (var, label) in enumerate([('nh4_mg_kg','NH\u2084\u207a'),('no3_mg_kg','NO\u2083\u207b')]):
    for j, depth in enumerate(['0-10','10-20']):
        ax = axes[i][j]
        sub = df[df['depth_cm']==depth]
        sns.boxplot(data=sub, x='year', y=var,
                    hue='treatment_label', ax=ax, palette='Set2')
        ax.set_title(f'{label} — {depth} cm')
        ax.set_xlabel('Year')
        ax.set_ylabel(f'{label} (mg/kg)')
        ax.legend(fontsize=7, title='Treatment')
        ax.grid(alpha=0.3)

plt.suptitle('N Distribution by Year, Depth, and Treatment', fontweight='bold')
plt.tight_layout()
plt.savefig('N_boxplots.png', dpi=150, bbox_inches='tight')
plt.show()

"""## 4. GEE Covariate Extraction"""

# ── EDIT YOUR GEE PROJECT ID ────────────────────────────────────────────────
GEE_PROJECT = '*project name*' #set your own project name
# ────────────────────────────────────────────────────────────────────────────

ee.Authenticate()
ee.Initialize(project=GEE_PROJECT)
print('GEE initialized.')

PLOTS = {
    101: {'lat': 41.16802171432988, 'lon': -96.43858599666265, 'treatment': 2},
    102: {'lat': 41.16802314205589, 'lon': -96.43825409190654, 'treatment': 1},
    103: {'lat': 41.16801885887779, 'lon': -96.43794684293230, 'treatment': 3},
    201: {'lat': 41.16818733033986, 'lon': -96.43858599666265, 'treatment': 3},
    202: {'lat': 41.16818161944992, 'lon': -96.43819529734974, 'treatment': 1},
    203: {'lat': 41.16819161350698, 'lon': -96.43794684293230, 'treatment': 2},
    301: {'lat': 41.16840577150589, 'lon': -96.43851771911282, 'treatment': 2},
    302: {'lat': 41.16841291009379, 'lon': -96.43822564292745, 'treatment': 1},
    303: {'lat': 41.16841291009379, 'lon': -96.43793735993927, 'treatment': 3},
}

# Sampling windows aligned to T0/T1/T2 timepoints
SAMPLING_WINDOWS = {
    2019: [('T0', '2019-05-01', '2019-08-31')],
    2020: [('T1', '2020-06-01', '2020-08-31'), ('T2', '2020-08-01', '2020-10-31')],
    2021: [('T1', '2021-06-01', '2021-08-31'), ('T2', '2021-08-01', '2021-10-31')],
    2022: [('T1', '2022-06-01', '2022-08-31'), ('T2', '2022-08-01', '2022-10-31')],
    2023: [('T1', '2023-06-01', '2023-08-31'), ('T2', '2023-08-01', '2023-10-31')],
}

def get_gee_covariates(lon, lat, start_date, end_date):
    point = ee.Geometry.Point([lon, lat]).buffer(15)

    # Sentinel-2 NDVI and EVI
    s2 = (ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
            .filterBounds(point)
            .filterDate(start_date, end_date)
            .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20))
            .median())
    ndvi = s2.normalizedDifference(['B8','B4']).rename('NDVI')
    evi  = s2.expression(
        '2.5 * ((NIR - RED) / (NIR + 6*RED - 7.5*BLUE + 1))',
        {'NIR': s2.select('B8'), 'RED': s2.select('B4'), 'BLUE': s2.select('B2')}
    ).rename('EVI')

    # Soil moisture proxy from Sentinel-1 SAR
    s1 = (ee.ImageCollection('COPERNICUS/S1_GRD')
            .filterBounds(point)
            .filterDate(start_date, end_date)
            .filter(ee.Filter.eq('instrumentMode', 'IW'))
            .select('VV')
            .median())

    result = (ndvi.addBands(evi).addBands(s1)
              .reduceRegion(
                  reducer=ee.Reducer.mean(),
                  geometry=point,
                  scale=10
              ))
    return result.getInfo()

# Extract all covariates
records = []
total = sum(len(v) for v in SAMPLING_WINDOWS.values()) * len(PLOTS)
count = 0

for plot_id, info in PLOTS.items():
    for year, windows in SAMPLING_WINDOWS.items():
        for (tp, start, end) in windows:
            count += 1
            print(f'[{count}/{total}] Plot {plot_id} | {year} | {tp}...', end=' ')
            try:
                vals = get_gee_covariates(info['lon'], info['lat'], start, end)
                records.append({
                    'plot_id':        plot_id,
                    'year':           year,
                    'time_point':     tp,
                    'treatment_code': info['treatment'],
                    'ndvi':           vals.get('NDVI'),
                    'evi':            vals.get('EVI'),
                    'sar_vv':         vals.get('VV'),
                })
                print('OK')
            except Exception as e:
                print(f'FAILED: {e}')
                records.append({
                    'plot_id': plot_id, 'year': year, 'time_point': tp,
                    'treatment_code': info['treatment'],
                    'ndvi': None, 'evi': None, 'sar_vv': None
                })

gee_df = pd.DataFrame(records)
print(f'\nGEE extraction complete: {gee_df.shape[0]} rows')
print('Missing values:')
print(gee_df[['ndvi','evi','sar_vv']].isnull().sum())
gee_df.head()

"""## 5. Aggregate & Merge Features"""

# Aggregate soil N to plot level — mean and std per plot x year x timepoint x depth x grazing
gpr_input = (
    df.groupby(['year','plot_id','treatment_code','treatment_label',
                'time_point','depth_cm','depth_numeric',
                'grazing','grazing_binary'], as_index=False)
    .agg(
        nh4_mean=('nh4_mg_kg','mean'),
        nh4_std=('nh4_mg_kg','std'),
        no3_mean=('no3_mg_kg','mean'),
        no3_std=('no3_mg_kg','std'),
        n_reps=('nh4_mg_kg','count')
    )
)

# Merge GEE covariates
gpr_input = gpr_input.merge(
    gee_df[['plot_id','year','time_point','ndvi','evi','sar_vv']],
    on=['plot_id','year','time_point'],
    how='left'
)

# Cap outliers at p90 to control GPR uncertainty
for col in ['nh4_mean','no3_mean']:
    p90 = gpr_input[col].quantile(0.90)
    gpr_input[col] = gpr_input[col].clip(upper=p90)
    print(f'{col} capped at {p90:.1f} mg/kg')

print(f'\nGPR input shape: {gpr_input.shape}')
print(f'Missing NDVI: {gpr_input["ndvi"].isnull().sum()}')
gpr_input.head()

"""## 6. RF Feature Selection with SPEI Index"""

# ── CELL B: Add SPEI Drought Index ───────────────────────────────────────────
# SPEI values for Nebraska 2019-2023 (negative = drought, positive = wet)
# Source: Vicente-Serrano et al. 2010 — pull from SPEI Global Drought Monitor
# or use manual values from the Nebraska Drought Monitor for your county

SPEI_ANNUAL = {
    2019:  0.850,   # slightly wet
    2020: -0.406,   # slightly dry
    2021: -0.783,   # slightly dry
    2022: -0.687,   # slightly dry
    2023: -0.896,   # dry
}

# Map SPEI into gpr_input by year
gpr_input['spei'] = gpr_input['year'].map(SPEI_ANNUAL)

print('SPEI values mapped:')
print(gpr_input.groupby('year')['spei'].first())

# Add spei to RF feature set and re-run importance
RF_FEATURES_SPEI = [
    'year', 'treatment_code', 'depth_numeric',
    'grazing_binary', 'ndvi', 'evi', 'sar_vv', 'spei'
]

results_with_spei = {}

for target, label in [('nh4_mean','NH\u2084\u207a'), ('no3_mean','NO\u2083\u207b')]:
    sub = gpr_input[RF_FEATURES_SPEI + [target]].dropna()
    X = sub[RF_FEATURES_SPEI]
    y = sub[target]

    rf = RandomForestRegressor(n_estimators=500, max_features='sqrt',
                                min_samples_leaf=3, random_state=42, n_jobs=-1)
    rf.fit(X, y)

    importances = pd.Series(rf.feature_importances_, index=RF_FEATURES_SPEI)
    importances = importances.sort_values(ascending=False)

    results_with_spei[target] = {
        'importances': importances,
        'label': label
    }

    print(f'\n=== {label} RF with SPEI ===')
    print(importances.round(4).to_string())

# Update top_features to include spei
FEATURE_LABELS['spei'] = 'SPEI (drought)'

# Plot RF feature importances side by side
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# The FEATURE_LABELS dictionary was already defined and updated. This re-definition would overwrite the 'spei' entry.
# Removing the re-definition to maintain the 'spei' entry.
# FEATURE_LABELS = {
#     'year':           'Year',
#     'treatment_code': 'Treatment',
#     'depth_numeric':  'Depth (cm)',
#     'grazing_binary': 'Grazing',
#     'ndvi':           'NDVI',
#     'evi':            'EVI',
#     'sar_vv':         'SAR VV (soil moisture)',
# }

for ax, (target, res) in zip(axes, results_with_spei.items()): # Use results_with_spei here
    imp = res['importances'].rename(index=FEATURE_LABELS)
    colors = ['#E53935' if v == imp.max() else '#1976D2' for v in imp.values]
    bars = ax.barh(imp.index[::-1], imp.values[::-1], color=colors[::-1])
    ax.set_xlabel('Feature Importance')
    ax.set_title(f'{res["label"]} \u2014 RF Importance Ranking (with SPEI)') # Added ' (with SPEI)' to title
    ax.grid(axis='x', alpha=0.3)
    # Value labels
    for bar, val in zip(bars, imp.values[::-1]):
        ax.text(val + 0.003, bar.get_y() + bar.get_height()/2,
                f'{val:.3f}', va='center', fontsize=9)

plt.suptitle('Random Forest Feature Importance (with SPEI)\n(Red = top predictor)',
             fontweight='bold')
plt.tight_layout()
plt.savefig('RF_feature_importance_with_SPEI.png', dpi=150, bbox_inches='tight') # Changed filename
plt.show()
print('Saved: RF_feature_importance_with_SPEI.png')

# Add spei to top features for GPR
for target in top_features:
    if 'spei' not in top_features[target]:
        top_features[target] = ['year', 'ndvi', 'sar_vv', 'spei']
    print(f'{target} features updated: {top_features[target]}')

# Select top N features for GPR — threshold at cumulative 80% importance (FIX THE MODEL TO INCLUDE THE NEW SPEI INDEX)
TOP_N = 5  # adjust based on RF output above

top_features = {}
for target, res in results_with_spei.items(): # Changed 'results' to 'results_with_spei'
    imp = res['importances']
    cum = imp.cumsum() / imp.sum()
    # Take features up to 80% cumulative importance, minimum 2
    n = max(2, (cum < 0.80).sum() + 1)
    top_features[target] = imp.head(min(n, TOP_N)).index.tolist()
    print(f'{res["label"]} top features: {top_features[target]}')

# Feature set for RF — includes grazing, treatment, depth, GEE covariates
RF_FEATURES = [
    'year',
    'treatment_code',
    'depth_numeric',
    'grazing_binary',   # ← grazing as a predictor
    'ndvi',
    'evi',
    'sar_vv',
    'spei'              # ← Added SPEI drought index
]

results_with_spei = {} # Changed to results_with_spei to align with downstream usage

for target, label in [('nh4_mean','NH₄ⁱ'), ('no3_mean','NO₃ⁱ')]:
    sub = gpr_input[RF_FEATURES + [target]].dropna()
    X = sub[RF_FEATURES]
    y = sub[target]

    rf = RandomForestRegressor(
        n_estimators=500,
        max_features='sqrt',
        min_samples_leaf=3,
        random_state=42,
        n_jobs=-1
    )
    rf.fit(X, y)

    # Cross-validated R2
    from sklearn.model_selection import LeaveOneGroupOut

    logo = LeaveOneGroupOut()
    groups = sub['year'].values
    cv_scores = cross_val_score(rf, X, y, cv=logo, groups=groups, scoring='r2')
    cv_r2 = cv_scores.mean()
    print(f'Leave-one-year-out R² scores: {cv_scores.round(3)}')
    print(f'Mean CV R²: {cv_r2:.3f}')

    # Feature importances
    importances = pd.Series(rf.feature_importances_, index=RF_FEATURES)
    importances = importances.sort_values(ascending=False)

    results_with_spei[target] = { # Changed to results_with_spei
        'importances': importances,
        'cv_r2': cv_r2,
        'label': label
    }

    print(f'\n=== {label} RF Results (with SPEI) ===') # Added ' (with SPEI)'
    print(f'Cross-validated R²: {cv_r2:.3f}')
    print('Feature importances:')
    print(importances.round(4).to_string())

"""## 7. GPR Modeling Using Top RF Features"""

def run_gpr_multifeature(data, target_col, features,
                          treatment_code, depth='0-10', grazing='No'):
    """
    GPR using top RF-selected features.
    Returns predicted mean, lower/upper CI, and observed training data.
    """
    sub = data[
        (data['treatment_code'] == treatment_code) &
        (data['depth_cm'] == depth) &
        (data['grazing'] == grazing)
    ].dropna(subset=[target_col] + features)

    if len(sub) < 3:
        print(f'  Skipping trt={treatment_code} depth={depth} grazing={grazing}: insufficient data ({len(sub)} rows)')
        return None

    X_train = sub[features].values.astype(float)
    y_raw   = sub[target_col].values
    y_train = np.log1p(y_raw)  # log transform

    # Normalize features
    X_mean = X_train.mean(axis=0)
    X_std  = X_train.std(axis=0) + 1e-8
    X_norm = (X_train - X_mean) / X_std

    kernel = Matern(nu=1.5) + WhiteKernel(noise_level=0.1)
    gpr = GaussianProcessRegressor(
        kernel=kernel,
        n_restarts_optimizer=10,
        normalize_y=True,
        random_state=42
    )
    gpr.fit(X_norm, y_train)

    # Build prediction grid: year varies 2019-2030, other features held at training mean
    years_pred = np.arange(2019, 2031)
    X_pred = np.tile(X_mean, (len(years_pred), 1))
    year_idx = features.index('year') if 'year' in features else 0
    X_pred[:, year_idx] = years_pred
    X_pred_norm = (X_pred - X_mean) / X_std

    y_log_mean, y_log_std = gpr.predict(X_pred_norm, return_std=True)

    y_mean  = np.expm1(y_log_mean)
    y_lower = np.clip(np.expm1(y_log_mean - 2*y_log_std), 0, None)
    y_upper = np.expm1(y_log_mean + 2*y_log_std)

    return {
        'years_pred': years_pred,
        'y_mean':     y_mean,
        'y_lower':    y_lower,
        'y_upper':    y_upper,
        'X_obs':      sub['year'].values,
        'y_obs':      y_raw,
    }

print('GPR function defined.')

"""## 8. Forecast Plots — 2019 to 2030 (0-10 cm)"""

TREATMENTS  = [1, 2, 3]
GRAZING_VALS = [('No', '-', 'Not Grazed'), ('Yes', '--', 'Grazed')]

for target, label in [('nh4_mean','NH\u2084\u207a'), ('no3_mean','NO\u2083\u207b')]:
    features = top_features[target]
    print(f'\nRunning GPR for {label} using features: {features}')

    fig, axes = plt.subplots(1, 3, figsize=(17, 5), sharey=True)

    for ax, trt in zip(axes, TREATMENTS):
        color = COLORS[trt]

        for grazing_val, ls, grazing_label in GRAZING_VALS:
            res = run_gpr_multifeature(
                gpr_input, target, features,
                treatment_code=trt, depth='0-10', grazing=grazing_val
            )
            if res is None:
                continue

            alpha = 0.15 if grazing_val == 'No' else 0.08
            ax.fill_between(res['years_pred'], res['y_lower'], res['y_upper'],
                            alpha=alpha, color=color)
            ax.plot(res['years_pred'], res['y_mean'],
                    color=color, linestyle=ls, lw=2,
                    label=f'GPR ({grazing_label})')
            ax.scatter(res['X_obs'], res['y_obs'],
                       color=color, s=40, zorder=5,
                       marker='o' if grazing_val=='No' else '^',
                       edgecolors='white', linewidths=0.5,
                       label=f'Obs ({grazing_label})')

        ax.axvline(2023.5, color='gray', linestyle=':', linewidth=1, alpha=0.7)
        ax.text(2024.0, ax.get_ylim()[1]*0.93 if ax.get_ylim()[1] > 0 else 1,
                'Forecast\u2192', fontsize=7, color='gray')
        ax.set_title(TREATMENT_LABELS[trt], fontsize=10, fontweight='bold')
        ax.set_xlabel('Year')
        ax.set_xlim(2018.5, 2030.5)
        ax.set_ylim(bottom=0)
        ax.grid(alpha=0.3)
        ax.legend(fontsize=7)

    axes[0].set_ylabel(f'{label} (mg/kg)')

    feat_str = ', '.join([FEATURE_LABELS.get(f, f) for f in features])
    plt.suptitle(
        f'{label} Trajectories by Treatment & Grazing (0-10 cm) — GPR Forecast to 2030\n'
        f'RF-selected features: {feat_str}',
        fontweight='bold', fontsize=11
    )
    plt.tight_layout()
    fname = f'GPR_forecast_{label.replace("\u207a","+").replace("\u207b","-")}_grazing_v2.png'
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.show()
    print(f'Saved: {fname}')

"""## Next Steps
- Add 10-20 cm depth analysis
- Add SPEI drought index as a temporal covariate to explicitly model the 2021 dip
- Export forecast table to CSV for reporting
- Compare grazed vs non-grazed trajectories statistically

## 8. Forecast Plots — 2019 to 2030 (10-20 cm)
"""

# ── CELL A: 10-20 cm Depth GPR Forecast ─────────────────────────────────────
for target, label in [('nh4_mean','NH\u2084\u207a'), ('no3_mean','NO\u2083\u207b')]:
    features = top_features[target]
    fig, axes = plt.subplots(1, 3, figsize=(17, 5), sharey=True)

    for ax, trt in zip(axes, TREATMENTS):
        color = COLORS[trt]
        for grazing_val, ls, grazing_label in GRAZING_VALS:
            res = run_gpr_multifeature(
                gpr_input, target, features,
                treatment_code=trt, depth='10-20', grazing=grazing_val
            )
            if res is None:
                continue
            alpha = 0.15 if grazing_val == 'No' else 0.08
            ax.fill_between(res['years_pred'], res['y_lower'], res['y_upper'],
                            alpha=alpha, color=color)
            ax.plot(res['years_pred'], res['y_mean'],
                    color=color, linestyle=ls, lw=2,
                    label=f'GPR ({grazing_label})')
            ax.scatter(res['X_obs'], res['y_obs'],
                       color=color, s=40, zorder=5,
                       marker='o' if grazing_val=='No' else '^',
                       edgecolors='white', linewidths=0.5,
                       label=f'Obs ({grazing_label})')

        ax.axvline(2023.5, color='gray', linestyle=':', linewidth=1, alpha=0.7)
        ax.text(2024.0, ax.get_ylim()[1]*0.93 if ax.get_ylim()[1] > 0 else 1,
                'Forecast\u2192', fontsize=7, color='gray')
        ax.set_title(TREATMENT_LABELS[trt], fontsize=10, fontweight='bold')
        ax.set_xlabel('Year')
        ax.set_xlim(2018.5, 2030.5)
        ax.set_ylim(bottom=0)
        ax.grid(alpha=0.3)
        ax.legend(fontsize=7)

    axes[0].set_ylabel(f'{label} (mg/kg)')
    plt.suptitle(
        f'{label} Trajectories by Treatment & Grazing (10-20 cm) — GPR Forecast to 2030',
        fontweight='bold', fontsize=11
    )
    plt.tight_layout()
    fname = f'GPR_forecast_{label.replace(chr(8314),"+").replace(chr(8315),"-")}_10-20cm.png'
    plt.savefig(fname, dpi=150, bbox_inches='tight')
    plt.show()
    print(f'Saved: {fname}')

"""## 11. Grazed vs Non Grazed Stat Comparison


"""

# ── CELL D: Grazed vs Non-Grazed Statistical Comparison ──────────────────────
from scipy import stats

print('=== Grazed vs Non-Grazed: Mann-Whitney U Test ===')
print('(Non-parametric — appropriate given non-normal N distributions)\n')

summary_records = []

for target, label in [('nh4_mg_kg','NH\u2084\u207a'), ('no3_mg_kg','NO\u2083\u207b')]:
    print(f'--- {label} ---')
    for trt in TREATMENTS:
        for year in sorted(df['year'].unique()):
            sub = df[(df['treatment_code']==trt) & (df['year']==year)]
            grazed     = sub[sub['grazing']=='Yes'][target].dropna()
            not_grazed = sub[sub['grazing']=='No'][target].dropna()

            if len(grazed) < 3 or len(not_grazed) < 3:
                continue

            stat, p = stats.mannwhitneyu(grazed, not_grazed, alternative='two-sided')
            sig = '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'

            summary_records.append({
                'variable':       label,
                'treatment':      TREATMENT_LABELS[trt],
                'year':           year,
                'mean_grazed':    round(grazed.mean(), 2),
                'mean_not_grazed':round(not_grazed.mean(), 2),
                'diff':           round(grazed.mean() - not_grazed.mean(), 2),
                'p_value':        round(p, 4),
                'significance':   sig
            })
            print(f'  Trt {trt} | {year}: G={grazed.mean():.1f} NG={not_grazed.mean():.1f} '
                  f'diff={grazed.mean()-not_grazed.mean():+.1f} p={p:.4f} {sig}')

stats_df = pd.DataFrame(summary_records)

# Plot significance heatmap
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
for ax, var in zip(axes, ['NH\u2084\u207a','NO\u2083\u207b']):
    sub = stats_df[stats_df['variable']==var].pivot(
        index='treatment', columns='year', values='diff'
    )
    p_sub = stats_df[stats_df['variable']==var].pivot(
        index='treatment', columns='year', values='p_value'
    )
    sns.heatmap(sub, ax=ax, cmap='RdBu_r', center=0, annot=True, fmt='.1f',
                linewidths=0.5, cbar_kws={'label': 'Mean diff (G - NG)'})

    # Overlay significance markers
    for i, trt in enumerate(sub.index):
        for j, yr in enumerate(sub.columns):
            try:
                p_val = p_sub.loc[trt, yr]
                sig = '***' if p_val<0.001 else '**' if p_val<0.01 else '*' if p_val<0.05 else ''
                if sig:
                    ax.text(j+0.5, i+0.8, sig, ha='center', fontsize=10, color='black')
            except:
                pass

    ax.set_title(f'{var} — Grazed minus Not Grazed (mg/kg)\n* p<0.05  ** p<0.01  *** p<0.001')
    ax.set_xlabel('Year')
    ax.set_ylabel('Treatment')

plt.suptitle('Grazing Effect on Soil N by Treatment and Year', fontweight='bold')
plt.tight_layout()
plt.savefig('grazing_effect_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()

# Export stats table
STATS_PATH = '/content/drive/MyDrive/ENREEC/NH4_NO3/grazing_stats_table.csv'
stats_df.to_csv(STATS_PATH, index=False)
print(f'\nStats table saved to: {STATS_PATH}')