# -*- coding: utf-8 -*-
"""Soil_Nitrogen_Pipeline_v3_1.ipynb

Automatically generated by Colab.

Original file is located at
    *google collab file*

# Soil Nitrogen Dynamics Pipeline v3.1

**Airori & Mamo — University of Nebraska-Lincoln**

**Changelog from v3.0:**
- GPR is now a SINGLE GLOBAL MODEL over all rows. v3.0 fit 18 separate
  models (treatment x grazing x depth), which made treatment, grazing and
  depth constants inside every fit — they could not carry effects.
- Treatment is one-hot encoded; grazing and depth enter as model dimensions.
  This is what "treatment-by-time trajectories" actually requires.
- ARD (anisotropic) Matern kernel: one length-scale per input dimension.
  Inverse length-scale gives a GPR-native relevance ranking that can be
  compared against RF importance — two independent methods, not a handoff.
- Temporal holdout: fit 2019-2022, predict 2023, report error metrics AND
  95% credible-interval coverage. This is what makes the uncertainty bounds
  "rigorously defined" rather than merely computed.
- SPEI is GEE-extracted per sampling window (GRIDMET/DROUGHT, spei90d),
  replacing the hand-typed annual dictionary used through v2.1.

**What has NOT changed:** five years is still five years. A global model does
not manufacture predictive skill. Expect leave-one-year-out R2 to stay
negative; the point is that covariates now do work inside the fit.

**Pipeline stages:**
1. Setup & load soil N data
2. Validate & summarize
3. Exploratory visualization
4. GEE covariates (NDVI, EVI, SAR VV) + SPEI per sampling window
5. GHG flux load & aggregation
6. GHG exploratory visualization
7. Aggregate & merge all features
8. Random Forest ranking (MDI) + permutation importance
9. Global GPR with ARD kernel
10. ARD relevance vs RF importance
11. Temporal holdout validation (2023)
12. Projection plots 2019-2028
13. Export forecast table
14. Grazed vs non-grazed statistical comparison

## 1. Setup & Load Soil N Data
"""

!pip install openpyxl scikit-learn matplotlib seaborn earthengine-api scipy -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

from sklearn.ensemble import RandomForestRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern, WhiteKernel
from sklearn.model_selection import LeaveOneGroupOut, cross_val_score
import ee
from google.colab import drive

drive.mount('/content/drive')
print('Libraries loaded successfully.')

# ── EDIT THIS PATH ──────────────────────────────────────────────────────────
FILE_PATH = 'path/to/data'   # set to your own data directory
# ────────────────────────────────────────────────────────────────────────────

df = pd.read_csv(FILE_PATH)

# Standardize grazing column
df['grazing'] = df['grazing'].str.strip().str.capitalize()
df['grazing_binary'] = (df['grazing'] == 'Yes').astype(int)

# Depth as numeric
df['depth_numeric'] = df['depth_cm'].map({'0-10': 5, '10-20': 15})

# Treatment label map
TREATMENT_LABELS = {
    1: 'Unfertilized Triticale',
    2: 'Fertilized Triticale',
    3: 'Triticale w/ Legume'
}
COLORS = {1: '#2196F3', 2: '#4CAF50', 3: '#FF9800'}
df['treatment_label'] = df['treatment_code'].map(TREATMENT_LABELS)

print(f'Loaded: {df.shape[0]} rows x {df.shape[1]} columns')
print(f'Years: {sorted(df["year"].unique())}')
print(f'Treatments: {df["treatment_code"].unique()}')
print(f'Grazing values: {df["grazing"].unique()}')
df.head()

"""## 2. Validate & Summarize"""

print('=== Missing values ===')
print(df[['nh4_mg_kg','no3_mg_kg']].isnull().sum())

print('\n=== Sample counts by year x treatment x grazing ===')
print(df.groupby(['year','treatment_code','grazing'])['sample_id'].count().to_string())

print('\n=== NH4+ summary stats ===')
print(df.groupby('treatment_code')['nh4_mg_kg'].describe().round(2))

print('\n=== NO3- summary stats ===')
print(df.groupby('treatment_code')['no3_mg_kg'].describe().round(2))

"""## 3. Exploratory Visualization"""

# Mean trajectories split by treatment and grazing
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
for ax, var, label in zip(axes,
                           ['nh4_mg_kg','no3_mg_kg'],
                           ['NH\u2084\u207a (mg/kg)','NO\u2083\u207b (mg/kg)']):
    for trt_code, trt_label in TREATMENT_LABELS.items():
        for grazing_val, ls in [('Yes','--'), ('No','-')]:
            sub = df[(df['treatment_code']==trt_code) & (df['grazing']==grazing_val)]
            yearly = sub.groupby('year')[var].mean()
            ax.plot(yearly.index, yearly.values,
                    color=COLORS[trt_code], linestyle=ls,
                    marker='o', linewidth=1.5,
                    label=f'{trt_label} ({grazing_val})')
    ax.set_title(label)
    ax.set_xlabel('Year')
    ax.set_ylabel(label)
    ax.legend(fontsize=7, ncol=2)
    ax.grid(alpha=0.3)

plt.suptitle('Mean N Trajectories by Treatment and Grazing (2019-2023)', fontweight='bold')
plt.tight_layout()
plt.savefig('N_trajectories_grazing.png', dpi=150, bbox_inches='tight')
plt.show()

# Boxplots by year, depth, treatment
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
for i, (var, label) in enumerate([('nh4_mg_kg','NH\u2084\u207a'),('no3_mg_kg','NO\u2083\u207b')]):
    for j, depth in enumerate(['0-10','10-20']):
        ax = axes[i][j]
        sub = df[df['depth_cm']==depth]
        sns.boxplot(data=sub, x='year', y=var,
                    hue='treatment_label', ax=ax, palette='Set2')
        ax.set_title(f'{label} — {depth} cm')
        ax.set_xlabel('Year')
        ax.set_ylabel(f'{label} (mg/kg)')
        ax.legend(fontsize=7, title='Treatment')
        ax.grid(alpha=0.3)
plt.suptitle('N Distribution by Year, Depth, and Treatment', fontweight='bold')
plt.tight_layout()
plt.savefig('N_boxplots.png', dpi=150, bbox_inches='tight')
plt.show()

"""## 4. GEE Covariate Extraction"""

# ── EDIT YOUR GEE PROJECT ID ────────────────────────────────────────────────
GEE_PROJECT = '*project name*' #set your own project name
# ────────────────────────────────────────────────────────────────────────────

ee.Authenticate()
ee.Initialize(project=GEE_PROJECT)
print('GEE initialized.')

PLOTS = {
    101: {'lat': 41.16802171432988, 'lon': -96.43858599666265, 'treatment': 2},
    102: {'lat': 41.16802314205589, 'lon': -96.43825409190654, 'treatment': 1},
    103: {'lat': 41.16801885887779, 'lon': -96.43794684293230, 'treatment': 3},
    201: {'lat': 41.16818733033986, 'lon': -96.43858599666265, 'treatment': 3},
    202: {'lat': 41.16818161944992, 'lon': -96.43819529734974, 'treatment': 1},
    203: {'lat': 41.16819161350698, 'lon': -96.43794684293230, 'treatment': 2},
    301: {'lat': 41.16840577150589, 'lon': -96.43851771911282, 'treatment': 2},
    302: {'lat': 41.16841291009379, 'lon': -96.43822564292745, 'treatment': 1},
    303: {'lat': 41.16841291009379, 'lon': -96.43793735993927, 'treatment': 3},
}

SAMPLING_WINDOWS = {
    2019: [('T0', '2019-05-01', '2019-08-31')],
    2020: [('T1', '2020-06-01', '2020-08-31'), ('T2', '2020-08-01', '2020-10-31')],
    2021: [('T1', '2021-06-01', '2021-08-31'), ('T2', '2021-08-01', '2021-10-31')],
    2022: [('T1', '2022-06-01', '2022-08-31'), ('T2', '2022-08-01', '2022-10-31')],
    2023: [('T1', '2023-06-01', '2023-08-31'), ('T2', '2023-08-01', '2023-10-31')],
}

def get_gee_covariates(lon, lat, start_date, end_date):
    point = ee.Geometry.Point([lon, lat]).buffer(15)
    s2 = (ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
            .filterBounds(point).filterDate(start_date, end_date)
            .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 20)).median())
    ndvi = s2.normalizedDifference(['B8','B4']).rename('NDVI')
    evi  = s2.expression(
        '2.5*((NIR-RED)/(NIR+6*RED-7.5*BLUE+1))',
        {'NIR':s2.select('B8'),'RED':s2.select('B4'),'BLUE':s2.select('B2')}
    ).rename('EVI')
    s1 = (ee.ImageCollection('COPERNICUS/S1_GRD')
            .filterBounds(point).filterDate(start_date, end_date)
            .filter(ee.Filter.eq('instrumentMode','IW'))
            .select('VV').median())
    result = (ndvi.addBands(evi).addBands(s1)
              .reduceRegion(reducer=ee.Reducer.mean(), geometry=point, scale=10))
    return result.getInfo()

records = []
total = sum(len(v) for v in SAMPLING_WINDOWS.values()) * len(PLOTS)
count = 0
for plot_id, info in PLOTS.items():
    for year, windows in SAMPLING_WINDOWS.items():
        for (tp, start, end) in windows:
            count += 1
            print(f'[{count}/{total}] Plot {plot_id} | {year} | {tp}...', end=' ')
            try:
                vals = get_gee_covariates(info['lon'], info['lat'], start, end)
                records.append({'plot_id': plot_id, 'year': year, 'time_point': tp,
                                'treatment_code': info['treatment'],
                                'ndvi': vals.get('NDVI'), 'evi': vals.get('EVI'),
                                'sar_vv': vals.get('VV')})
                print('OK')
            except Exception as e:
                print(f'FAILED: {e}')
                records.append({'plot_id': plot_id, 'year': year, 'time_point': tp,
                                'treatment_code': info['treatment'],
                                'ndvi': None, 'evi': None, 'sar_vv': None})

gee_df = pd.DataFrame(records)
print(f'\nGEE extraction complete: {gee_df.shape[0]} rows')
gee_df.head()

# ════════════════════════════════════════════════════════════════════════════
# CELL 4b: SPEI EXTRACTION FROM GRIDMET/DROUGHT
# ~4.6 km pixels — all 9 plots share one pixel, so SPEI varies by sampling
# window, not by plot. Bare point geometry: a sub-pixel buffer returns null.
# ════════════════════════════════════════════════════════════════════════════

SPEI_BANDS = ['spei30d', 'spei90d', 'spei180d']

SITE_LON = -96.43825
SITE_LAT = 41.16821


def get_spei(lon, lat, start_date, end_date):
    """Mean SPEI over the sampling window at several accumulation scales."""
    pt = ee.Geometry.Point([lon, lat])
    coll = (ee.ImageCollection('GRIDMET/DROUGHT')
              .filterBounds(pt)
              .filterDate(start_date, end_date)
              .select(SPEI_BANDS))

    n = coll.size().getInfo()
    if n == 0:
        raise ValueError(f'No GRIDMET images between {start_date} and {end_date}')

    vals = coll.mean().reduceRegion(
        reducer=ee.Reducer.mean(),
        geometry=pt,
        scale=4638
    ).getInfo()

    if all(v is None for v in vals.values()):
        raise ValueError(f'All bands null for {start_date}-{end_date}')
    return vals


spei_records = []
for year, windows in SAMPLING_WINDOWS.items():
    for (tp, start, end) in windows:
        print(f'SPEI | {year} | {tp}...', end=' ')
        try:
            vals = get_spei(SITE_LON, SITE_LAT, start, end)
            rec = {'year': year, 'time_point': tp}
            rec.update({b: vals.get(b) for b in SPEI_BANDS})
            spei_records.append(rec)
            print('OK')
        except Exception as e:
            print(f'FAILED: {e}')
            rec = {'year': year, 'time_point': tp}
            rec.update({b: None for b in SPEI_BANDS})
            spei_records.append(rec)

spei_df = pd.DataFrame(spei_records)
print(f'\nSPEI extracted: {spei_df.shape[0]} rows')
print(spei_df.round(3).to_string(index=False))

# ── Does SPEI now vary within years? ────────────────────────────────────────
print('Unique values per band:')
for b in SPEI_BANDS:
    valid = spei_df[['year', b]].dropna()
    if len(valid) < 3:
        print(f'  {b}: insufficient data ({len(valid)} rows)')
        continue
    r, p = stats.pearsonr(valid['year'], valid[b])
    print(f'  {b}: r = {r:+.3f}, p = {p:.3f}')

print('\nCorrelation among SPEI timescales:')
print(spei_df[SPEI_BANDS].corr().round(3).to_string())

print('\n2021 check — should be the most negative year:')
print(spei_df[spei_df['year']==2021][['time_point'] + SPEI_BANDS].round(3).to_string(index=False))

"""## 5. ⭐ GHG Flux Data — Load & Aggregate
> **PLACEHOLDER — plug in your GHG data here when ready.**
>
> **Expected input file format:**
> One CSV file with these columns (one row per chamber measurement):
> ```
> plot_id | date | co2_flux | n2o_flux | ch4_flux
> ```
> - `plot_id`: 101–303 (must match soil N plot IDs)
> - `date`: YYYY-MM-DD format
> - `co2_flux`: CO₂ flux in kg/ha/d
> - `ch4_flux`: CH₄ flux in g/ha/d
> - `n2o_flux`: N₂O flux in g/ha/d
>
> **Coverage:** 2020–2023 only. 2019 has no GHG data (T0 baseline).
> Rows with missing plot_id or date will be dropped automatically.
"""

# ════════════════════════════════════════════════════════════════════════════
# CELL 5: GHG FLUX DATA LOAD — Hutchinson-Mosier method, per ha/day units
# ════════════════════════════════════════════════════════════════════════════

# ── EDIT THIS PATH ──────────────────────────────────────────────────────────
GHG_FILE_PATH = '/content/drive/MyDrive/ENREEC/GHG/GHG_Master.xlsx'
# ────────────────────────────────────────────────────────────────────────────

ghg_raw = pd.read_excel(GHG_FILE_PATH)

# Strip G/NG suffix from plot_id — extract numeric part only
ghg_raw['plot_id'] = ghg_raw['plot_id'].str.extract(r'(\d+)').astype(int)

# Parse date and extract year
ghg_raw['date'] = pd.to_datetime(ghg_raw['date'])
ghg_raw['year'] = ghg_raw['date'].dt.year

# Grazing already standardized as Yes/No — matches soil N file
# Drop 2019 — no GHG collected at T0 baseline
ghg_raw = ghg_raw[ghg_raw['year'] >= 2020].copy()

print(f'GHG raw: {ghg_raw.shape[0]} rows')
print(f'Years: {sorted(ghg_raw["year"].unique())}')
print(f'Plots: {sorted(ghg_raw["plot_id"].unique())}')
print(f'Grazing values: {ghg_raw["grazing"].unique()}')
print(f'\nSampling dates per year:')
print(ghg_raw.groupby("year")["date"].nunique())
print(f'\nMissing values:')
print(ghg_raw[["co2_kg_ha_d","ch4_g_ha_d","n2o_g_ha_d"]].isnull().sum())
print(f'\nNegative values:')
print('CO2:', (ghg_raw["co2_kg_ha_d"] < 0).sum())
print('CH4:', (ghg_raw["ch4_g_ha_d"] < 0).sum())
print('N2O:', (ghg_raw["n2o_g_ha_d"] < 0).sum())
ghg_raw.head(10)

# Find extreme outliers before plotting
print('=== Top 5 CH4 values ===')
print(ghg_raw.nlargest(5, 'ch4_g_ha_d')[['plot_id','date','grazing','ch4_g_ha_d']])

print('\n=== Top 5 CO2 values ===')
print(ghg_raw.nlargest(5, 'co2_kg_ha_d')[['plot_id','date','grazing','co2_kg_ha_d']])

"""## 6. GHG Exploratory Visualization"""

# ════════════════════════════════════════════════════════════════════════════
# CELL 6: GHG EXPLORATORY VISUALIZATION
# ════════════════════════════════════════════════════════════════════════════

PLOT_TREATMENT = {101:2,102:1,103:3,201:3,202:1,203:2,301:2,302:1,303:3}
ghg_raw['treatment_code']  = ghg_raw['plot_id'].map(PLOT_TREATMENT)
ghg_raw['treatment_label'] = ghg_raw['treatment_code'].map(TREATMENT_LABELS)

# ── Plot 1: Mean GHG trajectories by treatment and grazing ──────────────────
fig, axes = plt.subplots(1, 3, figsize=(17, 5))

ghg_vars = [
    ('co2_kg_ha_d', 'CO\u2082 flux (kg/ha/day)'),
    ('ch4_g_ha_d',  'CH\u2084 flux (g/ha/day)'),
    ('n2o_g_ha_d',  'N\u2082O flux (g/ha/day)'),
]

for ax, (var, label) in zip(axes, ghg_vars):
    for trt_code, trt_label in TREATMENT_LABELS.items():
        for grazing_val, ls in [('No', '-'), ('Yes', '--')]:
            sub = ghg_raw[
                (ghg_raw['treatment_code'] == trt_code) &
                (ghg_raw['grazing'] == grazing_val)
            ]
            yearly = sub.groupby('year')[var].mean()
            ax.plot(yearly.index, yearly.values,
                    color=COLORS[trt_code], linestyle=ls,
                    marker='o', linewidth=1.8,
                    label=f'{trt_label} ({"Grazed" if grazing_val=="Yes" else "Not Grazed"})')

    # Drought marker
    ax.axvline(2021, color='gray', linestyle=':', linewidth=1, alpha=0.6)
    ax.text(2021.05, ax.get_ylim()[1] * 0.97,
            '2021\ndrought', fontsize=7, color='gray', va='top')

    # Zero flux reference line
    ax.axhline(0, color='black', linewidth=0.5, alpha=0.4)

    ax.set_title(label, fontsize=10, fontweight='bold')
    ax.set_xlabel('Year')
    ax.set_ylabel(label)
    ax.legend(fontsize=6, ncol=1)
    ax.grid(alpha=0.3)
    ax.set_xticks([2020, 2021, 2022, 2023])

plt.suptitle('GHG Flux Trajectories by Treatment and Grazing (2020\u20132023)',
             fontweight='bold', fontsize=12)
plt.tight_layout()
plt.savefig('GHG_trajectories.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: GHG_trajectories.png')

# ── Plot 2: Boxplots by year and treatment ───────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(17, 5))

for ax, (var, label) in zip(axes, ghg_vars):
    sns.boxplot(data=ghg_raw, x='year', y=var,
                hue='treatment_label', ax=ax,
                palette='Set2', fliersize=3)
    ax.axhline(0, color='black', linewidth=0.5, alpha=0.4)
    ax.set_title(label, fontsize=10, fontweight='bold')
    ax.set_xlabel('Year')
    ax.set_ylabel(label)
    ax.legend(fontsize=7, title='Treatment')
    ax.grid(alpha=0.3)

plt.suptitle('GHG Flux Distribution by Year and Treatment',
             fontweight='bold', fontsize=12)
plt.tight_layout()
plt.savefig('GHG_boxplots.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: GHG_boxplots.png')

# ── Plot 3: Grazed vs Non-Grazed GHG difference by year ─────────────────────
ghg_pivot = ghg_raw.groupby(['year','treatment_label','grazing'])[
    ['co2_kg_ha_d','n2o_g_ha_d','ch4_g_ha_d']
].mean().reset_index()

fig, axes = plt.subplots(1, 3, figsize=(17, 5))

for ax, (var, label) in zip(axes, ghg_vars):
    grazed     = ghg_pivot[ghg_pivot['grazing']=='Yes'].set_index(['year','treatment_label'])[var]
    not_grazed = ghg_pivot[ghg_pivot['grazing']=='No'].set_index(['year','treatment_label'])[var]
    diff = (grazed - not_grazed).reset_index()
    diff.columns = ['year','treatment_label','diff']

    for trt_code, trt_label in TREATMENT_LABELS.items():
        sub = diff[diff['treatment_label']==trt_label]
        ax.plot(sub['year'], sub['diff'],
                color=COLORS[trt_code], marker='o',
                linewidth=1.8, label=trt_label)

    ax.axhline(0, color='black', linewidth=0.8, linestyle='--', alpha=0.5)
    ax.axvline(2021, color='gray', linestyle=':', linewidth=1, alpha=0.6)
    ax.set_title(f'{label}\nGrazed minus Not Grazed', fontsize=10, fontweight='bold')
    ax.set_xlabel('Year')
    ax.set_ylabel('Difference (G \u2212 NG)')
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)
    ax.set_xticks([2020, 2021, 2022, 2023])

plt.suptitle('Grazing Effect on GHG Flux by Treatment (2020\u20132023)\n'
             'Positive = grazing increases flux, Negative = grazing reduces flux',
             fontweight='bold', fontsize=11)
plt.tight_layout()
plt.savefig('GHG_grazing_effect.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: GHG_grazing_effect.png')

# ── Plot 4: N2O vs NO3- mechanistic scatter ──────────────────────────────────
# Merge annual NO3 mean with annual GHG mean for correlation check
no3_annual = (
    df.groupby(['plot_id','year'], as_index=False)
    ['no3_mg_kg'].mean()
    .rename(columns={'no3_mg_kg': 'no3_mean'})
)

ghg_for_scatter = (
    ghg_raw.groupby(['plot_id','year'], as_index=False)
    [['n2o_g_ha_d','co2_kg_ha_d']].mean()
)

scatter_df = ghg_for_scatter.merge(no3_annual, on=['plot_id','year'], how='inner')
scatter_df['treatment_code']  = scatter_df['plot_id'].map(PLOT_TREATMENT)
scatter_df['treatment_label'] = scatter_df['treatment_code'].map(TREATMENT_LABELS)

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

for ax, (x_var, x_label) in zip(axes, [
    ('no3_mean',    'NO\u2083\u207b (mg/kg)'),
    ('co2_kg_ha_d', 'CO\u2082 flux (kg/ha/day)'),
]):
    for trt_code, trt_label in TREATMENT_LABELS.items():
        sub = scatter_df[scatter_df['treatment_code'] == trt_code]
        ax.scatter(sub[x_var], sub['n2o_g_ha_d'],
                   color=COLORS[trt_code], label=trt_label,
                   alpha=0.75, s=60, edgecolors='white', linewidths=0.5)

    # Pearson correlation
    valid = scatter_df[[x_var,'n2o_g_ha_d']].dropna()
    if len(valid) > 3:
        r, p = stats.pearsonr(valid[x_var], valid['n2o_g_ha_d'])
        sig = '***' if p<0.001 else '**' if p<0.01 else '*' if p<0.05 else 'ns'
        ax.set_title(f'N\u2082O vs {x_label}\nr = {r:.2f}, p = {p:.3f} {sig}',
                     fontsize=10, fontweight='bold')

    ax.axhline(0, color='black', linewidth=0.5, alpha=0.4)
    ax.set_xlabel(x_label)
    ax.set_ylabel('N\u2082O flux (g/ha/day)')
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

plt.suptitle('N\u2082O Flux Mechanistic Check\n'
             '(Expected: positive correlation with NO\u2083\u207b via denitrification)',
             fontweight='bold', fontsize=11)
plt.tight_layout()
plt.savefig('GHG_N2O_mechanistic.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: GHG_N2O_mechanistic.png')

"""## 7. Aggregate & Merge All Features"""

# ════════════════════════════════════════════════════════════════════════════
# CELL 7: AGGREGATE GHG + MERGE ALL FEATURES
# ════════════════════════════════════════════════════════════════════════════

# ── Step 1: Aggregate GHG to seasonal mean per plot × year × grazing ────────
ghg_annual = (
    ghg_raw.groupby(['plot_id', 'year', 'grazing'], as_index=False)
    .agg(
        co2_mean = ('co2_kg_ha_d', 'mean'),
        co2_std  = ('co2_kg_ha_d', 'std'),
        ch4_mean = ('ch4_g_ha_d',  'mean'),
        ch4_std  = ('ch4_g_ha_d',  'std'),
        n2o_mean = ('n2o_g_ha_d',  'mean'),
        n2o_std  = ('n2o_g_ha_d',  'std'),
        n_dates  = ('date',        'nunique'),
    )
)

PLOT_TREATMENT = {101:2,102:1,103:3,201:3,202:1,203:2,301:2,302:1,303:3}
ghg_annual['treatment_code']  = ghg_annual['plot_id'].map(PLOT_TREATMENT)
ghg_annual['treatment_label'] = ghg_annual['treatment_code'].map(TREATMENT_LABELS)

print(f'GHG aggregated: {ghg_annual.shape[0]} rows')
print(f'Expected: {9 * 2 * 4} = 72 rows (9 plots x 2 grazing x 4 years)')
print(f'\nSampling dates used per year:')
print(ghg_annual.groupby('year')['n_dates'].agg(['mean','min','max']).round(1))
print(f'\nMissing GHG values after aggregation:')
print(ghg_annual[['co2_mean','ch4_mean','n2o_mean']].isnull().sum())

# ── Step 2: Aggregate soil N to plot level ───────────────────────────────────
gpr_input = (
    df.groupby(['year','plot_id','treatment_code','treatment_label',
                'time_point','depth_cm','depth_numeric',
                'grazing','grazing_binary'], as_index=False)
    .agg(
        nh4_mean = ('nh4_mg_kg', 'mean'),
        nh4_std  = ('nh4_mg_kg', 'std'),
        no3_mean = ('no3_mg_kg', 'mean'),
        no3_std  = ('no3_mg_kg', 'std'),
        n_reps   = ('nh4_mg_kg', 'count')
    )
)

# ── Step 3: Merge GEE covariates ─────────────────────────────────────────────
gpr_input = gpr_input.merge(
    gee_df[['plot_id','year','time_point','ndvi','evi','sar_vv']],
    on=['plot_id','year','time_point'], how='left'
)

# ── Step 4: Merge SPEI (GRIDMET/DROUGHT, per sampling window) ───────────────
gpr_input = gpr_input.merge(spei_df, on=['year', 'time_point'], how='left')

# The three timescales correlate 0.85-0.89, so use one — including all three
# would split importance the way NDVI/EVI already do. 90d is the least
# year-collinear (r = -0.24) and matches the timescale soil N responds to.
SPEI_CHOICE = 'spei90d'
gpr_input['spei'] = gpr_input[SPEI_CHOICE]

print(f'SPEI: using {SPEI_CHOICE}')
print(gpr_input.groupby(['year','time_point'])['spei'].first().round(3).to_string()

)

# ── Step 5: Merge GHG — keyed on plot_id + year + grazing ───────────────────
# Note: grazing is now part of the merge key since GHG has
# separate grazed/non-grazed measurements
# 2019 rows will have NaN for GHG — expected, no GHG at T0
gpr_input = gpr_input.merge(
    ghg_annual[['plot_id','year','grazing','co2_mean','ch4_mean','n2o_mean']],
    on=['plot_id','year','grazing'], how='left'
)

# ── Step 6: Cap soil N outliers at p90 ──────────────────────────────────────
for col in ['nh4_mean','no3_mean']:
    p90 = gpr_input[col].quantile(0.90)
    gpr_input[col] = gpr_input[col].clip(upper=p90)
    print(f'{col} capped at {p90:.1f} mg/kg')

# ── Step 7: Summary ──────────────────────────────────────────────────────────
print(f'\nFinal GPR input shape: {gpr_input.shape}')
print(f'\nMissing values per covariate:')
print(gpr_input[['ndvi','evi','sar_vv','spei',
                  'co2_mean','ch4_mean','n2o_mean']].isnull().sum())
print(f'\nGHG NaN rows by year (2019 expected):')
print(gpr_input[gpr_input['co2_mean'].isnull()].groupby('year').size())
gpr_input.head(10)

"""## 8. Random Forest Feature Selection"""

# ════════════════════════════════════════════════════════════════════════════
# CELL 8: RANDOM FOREST FEATURE SELECTION
# ════════════════════════════════════════════════════════════════════════════

RF_FEATURES = [
    'year',
    'treatment_code',
    'depth_numeric',
    'grazing_binary',
    'ndvi',
    'evi',
    'sar_vv',
    'spei',
    'co2_mean',    # GHG — soil respiration proxy
    'ch4_mean',    # GHG — secondary
    'n2o_mean',    # GHG — N transformation proxy
]

FEATURE_LABELS = {
    'year':           'Year',
    'treatment_code': 'Treatment',
    'depth_numeric':  'Depth (cm)',
    'grazing_binary': 'Grazing',
    'ndvi':           'NDVI',
    'evi':            'EVI',
    'sar_vv':         'SAR VV (soil moisture)',
    'spei':           'SPEI (drought)',
    'co2_mean':       'CO\u2082 flux',
    'ch4_mean':       'CH\u2084 flux',
    'n2o_mean':       'N\u2082O flux',
}

results = {}

for target, label in [('nh4_mean','NH\u2084\u207a'), ('no3_mean','NO\u2083\u207b')]:
    sub = gpr_input[RF_FEATURES + [target]].dropna()
    X = sub[RF_FEATURES]
    y = sub[target]

    rf = RandomForestRegressor(
        n_estimators=500, max_features='sqrt',
        min_samples_leaf=3, random_state=42, n_jobs=-1
    )
    rf.fit(X, y)

    # Leave-one-year-out CV
    logo   = LeaveOneGroupOut()
    groups = sub['year'].values
    cv_scores = cross_val_score(
        rf, X, y, cv=logo, groups=groups, scoring='r2'
    )

    importances = pd.Series(
        rf.feature_importances_, index=RF_FEATURES
    ).sort_values(ascending=False)

    results[target] = {
        'importances': importances,
        'cv_scores':   cv_scores,
        'label':       label
    }

    print(f'\n=== {label} RF Results ===')
    print(f'Leave-one-year-out R² per fold: {cv_scores.round(3)}')
    print(f'Mean CV R²: {cv_scores.mean():.3f}')
    print('Feature importances (covariate ranking only):')
    print(importances.round(4).to_string())

# ── Feature importance plot ──────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

for ax, (target, res) in zip(axes, results.items()):
    imp = res['importances'].rename(index=FEATURE_LABELS)
    colors = [
        '#E53935' if v == imp.max() else
        '#FF7043' if v >= imp.quantile(0.75) else
        '#1976D2'
        for v in imp.values
    ]
    bars = ax.barh(imp.index[::-1], imp.values[::-1], color=colors[::-1])
    for bar, val in zip(bars, imp.values[::-1]):
        ax.text(val + 0.002, bar.get_y() + bar.get_height()/2,
                f'{val:.3f}', va='center', fontsize=8)
    ax.set_xlabel('Feature Importance')
    ax.set_title(
        f'{res["label"]} — RF Importance Ranking (v3.0)\n'
        f'Used for covariate prioritization only',
        fontsize=10
    )
    ax.grid(axis='x', alpha=0.3)

plt.suptitle(
    'Random Forest Feature Importance (with GHG Covariates)\n'
    'Red = top predictor | Orange = top quartile',
    fontweight='bold', fontsize=12
)
plt.tight_layout()
plt.savefig('RF_feature_importance_v3.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: RF_feature_importance_v3.png')

# ── Select top features for GPR ──────────────────────────────────────────────
TOP_N = 5  # allows GHG features to enter alongside GEE and SPEI

top_features = {}
for target, res in results.items():
    imp = res['importances']
    cum = imp.cumsum() / imp.sum()
    n   = max(2, (cum < 0.80).sum() + 1)
    top_features[target] = imp.head(min(n, TOP_N)).index.tolist()
    print(f'\n{res["label"]} top features: {top_features[target]}')

"""## Permutation Importance"""

# ════════════════════════════════════════════════════════════════════════════
# CELL 8b: PERMUTATION IMPORTANCE (robustness check on MDI ranking)
# ────────────────────────────────────────────────────────────────────────────
# MDI (Cell 8) is biased toward high-cardinality features — continuous
# covariates get more candidate split points than binary ones like
# grazing_binary. Permutation importance is model-agnostic and does not
# inherit that bias, so it tests whether the MDI ranking holds up.
# ════════════════════════════════════════════════════════════════════════════

from sklearn.inspection import permutation_importance
from sklearn.model_selection import GroupShuffleSplit

perm_results = {}

for target, label in [('nh4_mean','NH\u2084\u207a'), ('no3_mean','NO\u2083\u207b')]:
    sub = gpr_input[RF_FEATURES + [target]].dropna()
    X = sub[RF_FEATURES]
    y = sub[target]
    groups = sub['year'].values

    # Hold out one year so importance is measured on unseen data.
    # Grouping by year prevents the same year appearing in train and test.
    gss = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=42)
    train_idx, test_idx = next(gss.split(X, y, groups=groups))

    rf = RandomForestRegressor(
        n_estimators=500, max_features='sqrt',
        min_samples_leaf=3, random_state=42, n_jobs=-1
    )
    rf.fit(X.iloc[train_idx], y.iloc[train_idx])

    perm = permutation_importance(
        rf, X.iloc[test_idx], y.iloc[test_idx],
        n_repeats=50,
        random_state=42,
        scoring='neg_mean_squared_error',
        n_jobs=-1
    )

    perm_mean = pd.Series(perm.importances_mean, index=RF_FEATURES)
    perm_std  = pd.Series(perm.importances_std,  index=RF_FEATURES)

    # Normalize to shares so the scale is comparable to MDI.
    # Negative values mean shuffling IMPROVED prediction — i.e. the feature
    # is noise. Clip at zero before normalizing.
    perm_pos  = perm_mean.clip(lower=0)
    perm_norm = perm_pos / perm_pos.sum() if perm_pos.sum() > 0 else perm_pos

    perm_results[target] = {
        'raw':   perm_mean.sort_values(ascending=False),
        'std':   perm_std,
        'norm':  perm_norm.sort_values(ascending=False),
        'label': label,
        'n_train': len(train_idx),
        'n_test':  len(test_idx),
    }

    print(f'\n=== {label} — Permutation Importance ===')
    print(f'Train n={len(train_idx)} | Test n={len(test_idx)}')
    print('(raw = MSE increase when shuffled; negative = feature is noise)')
    comp = pd.DataFrame({
        'MDI':        results[target]['importances'],
        'Perm_raw':   perm_mean,
        'Perm_std':   perm_std,
        'Perm_share': perm_norm,
    }).sort_values('Perm_raw', ascending=False)
    print(comp.round(4).to_string())

# ── Side-by-side MDI vs permutation comparison ──────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(16, 11))

for row, (target, pres) in enumerate(perm_results.items()):
    # Left: MDI
    ax = axes[row][0]
    mdi = results[target]['importances'].rename(index=FEATURE_LABELS)
    ax.barh(mdi.index[::-1], mdi.values[::-1], color='#1976D2')
    ax.set_xlabel('MDI importance (share)')
    ax.set_title(f'{pres["label"]} — MDI (in-sample, impurity-based)',
                 fontsize=10, fontweight='bold')
    ax.grid(axis='x', alpha=0.3)

    # Right: permutation, with SD error bars
    ax = axes[row][1]
    raw = pres['raw'].rename(index=FEATURE_LABELS)
    sd  = pres['std'].rename(index=FEATURE_LABELS).reindex(raw.index)
    # Grey out features that are indistinguishable from noise
    bar_colors = ['#BDBDBD' if v <= 0 else '#E53935' for v in raw.values]
    ax.barh(raw.index[::-1], raw.values[::-1],
            xerr=sd.values[::-1], color=bar_colors[::-1],
            error_kw={'linewidth': 0.8, 'ecolor': '#555555'})
    ax.axvline(0, color='black', linewidth=0.8)
    ax.set_xlabel('MSE increase when shuffled (\u00b1 SD)')
    ax.set_title(f'{pres["label"]} — Permutation (held-out year)\n'
                 f'grey = at or below zero (noise)',
                 fontsize=10, fontweight='bold')
    ax.grid(axis='x', alpha=0.3)

plt.suptitle(
    'Covariate Importance: MDI vs Permutation\n'
    'Agreement between methods indicates a robust ranking',
    fontweight='bold', fontsize=12
)
plt.tight_layout()
plt.savefig('RF_importance_MDI_vs_permutation.png', dpi=150, bbox_inches='tight')
plt.show()

# ── Rank-shift table: does the story change? ────────────────────────────────
print('\n' + '='*70)
print('RANK COMPARISON — does the MDI story hold up?')
print('='*70)

for target, pres in perm_results.items():
    mdi_rank  = results[target]['importances'].rank(ascending=False)
    perm_rank = pres['raw'].rank(ascending=False)
    shift = pd.DataFrame({
        'MDI_rank':  mdi_rank,
        'Perm_rank': perm_rank,
        'shift':     mdi_rank - perm_rank,
    }).sort_values('MDI_rank')
    shift.index = [FEATURE_LABELS.get(i, i) for i in shift.index]
    print(f'\n{pres["label"]}  (positive shift = ranked higher by permutation)')
    print(shift.astype(int).to_string())

"""## 9. Global GPR Model

v3.0 filtered to one treatment x grazing x depth subset before fitting, so
those three variables had zero variance inside every model and contributed
nothing — the visible separation between panel lines came from fitting
different subsets, not from a modelled effect.

Here one model sees all rows, with treatment one-hot encoded (1/2/3 as a
number would wrongly imply Fertilized sits "between" Unfertilized and
Legume) and grazing and depth as real dimensions.
"""

# ════════════════════════════════════════════════════════════════════════════
# CELL 9: GLOBAL GPR WITH ARD KERNEL
# ════════════════════════════════════════════════════════════════════════════
from sklearn.gaussian_process.kernels import Matern, WhiteKernel, ConstantKernel

# Features that describe experimental STRUCTURE — always included as model
# dimensions, never as filters. Stripped from the RF-selected list so they
# are not added twice.
STRUCTURAL = ['treatment_code', 'depth_numeric', 'grazing_binary']


def build_global_gpr(data, target_col, rf_selected, verbose=True):
    """One GPR over all rows. Returns fitted model + scaling metadata."""
    d = data.copy()

    # One-hot treatment
    trt_dummies = pd.get_dummies(d['treatment_code'], prefix='trt').astype(float)
    d = pd.concat([d, trt_dummies], axis=1)

    continuous = [f for f in rf_selected if f not in STRUCTURAL]
    feats = continuous + list(trt_dummies.columns) + ['grazing_binary', 'depth_numeric']

    cols = list(dict.fromkeys(feats + [target_col, 'year']))
    sub = d[cols].dropna()
    X = sub[feats].values.astype(float)
    y = np.log1p(sub[target_col].values)

    X_mean = X.mean(axis=0)
    X_std  = X.std(axis=0) + 1e-8
    X_norm = (X - X_mean) / X_std

    # ARD: one length-scale per dimension. Short length-scale = the fitted
    # function varies quickly along that axis = that covariate matters.
    kernel = (ConstantKernel(1.0)
              * Matern(length_scale=np.ones(X.shape[1]), nu=1.5)
              + WhiteKernel(noise_level=0.1))

    gpr = GaussianProcessRegressor(
        kernel=kernel, n_restarts_optimizer=5,
        normalize_y=True, random_state=42
    )
    gpr.fit(X_norm, y)

    if verbose:
        print(f'  n = {len(sub)} rows, {len(feats)} dimensions')
        print(f'  features: {feats}')
        print(f'  log-marginal-likelihood: {gpr.log_marginal_likelihood_value_:.2f}')

    return {
        'gpr': gpr, 'feats': feats, 'continuous': continuous,
        'trt_cols': list(trt_dummies.columns),
        'X_mean': X_mean, 'X_std': X_std,
        'n': len(sub), 'data': sub, 'target': target_col,
    }


global_models = {}
for target, label in [('nh4_mean', 'NH\u2084\u207a'), ('no3_mean', 'NO\u2083\u207b')]:
    print(f'\n=== Fitting global GPR: {label} ===')
    global_models[target] = build_global_gpr(
        gpr_input, target, top_features[target]
    )
    global_models[target]['label'] = label

"""## 10. ARD Relevance vs RF Importance

The GP learns a separate length-scale for every input dimension. A short
length-scale means the fitted surface changes rapidly along that axis, which
is the GP's own statement about which covariates matter — arrived at by a
completely different mechanism than RF's impurity accounting.

Where the two agree, the claim is strong. Where they diverge, that gap is
itself a result worth explaining.
"""

# ════════════════════════════════════════════════════════════════════════════
# CELL 10: ARD LENGTH-SCALES vs RF IMPORTANCE
# ════════════════════════════════════════════════════════════════════════════

def ard_relevance(model):
    """Inverse length-scale, normalized to shares."""
    ls = np.atleast_1d(np.asarray(model['gpr'].kernel_.k1.k2.length_scale))
    if len(ls) != len(model['feats']):
        raise ValueError(
            f'{len(ls)} length-scales vs {len(model["feats"])} features — '
            f're-run Cell 9 to refit against the current top_features.'
        )
    rel = pd.Series(1.0 / ls, index=model['feats'])
    return (rel / rel.sum()).sort_values(ascending=False)


ARD_LABELS = dict(FEATURE_LABELS)
ARD_LABELS.update({
    'trt_1': 'Treatment: Unfertilized',
    'trt_2': 'Treatment: Fertilized',
    'trt_3': 'Treatment: Legume',
})

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

for ax, (target, model) in zip(axes, global_models.items()):
    ard = ard_relevance(model)
    print(f'\n=== {model["label"]} — ARD relevance (GPR-native) ===')
    print(ard.round(4).to_string())

    # Side-by-side with RF where the feature exists in both
    rf_imp = results[target]['importances']
    comp = pd.DataFrame({
        'ARD': ard,
        'RF':  rf_imp.reindex(ard.index),
    })
    comp.index = [ARD_LABELS.get(i, i) for i in comp.index]
    comp = comp.sort_values('ARD', ascending=True)

    ypos = np.arange(len(comp))
    ax.barh(ypos - 0.2, comp['ARD'], height=0.4,
            color='#7F77DD', label='GPR (ARD)')
    ax.barh(ypos + 0.2, comp['RF'].fillna(0), height=0.4,
            color='#1D9E75', label='RF (MDI)')
    ax.set_yticks(ypos)
    ax.set_yticklabels(comp.index, fontsize=9)
    ax.set_xlabel('Relevance / importance (share)')
    ax.set_title(f'{model["label"]} — two independent rankings', fontsize=10)
    ax.legend(fontsize=8)
    ax.grid(axis='x', alpha=0.3)

plt.suptitle(
    'Covariate relevance: GPR length-scales vs RF importance\n'
    'One-hot treatment terms have no RF counterpart (RF used treatment_code)',
    fontweight='bold', fontsize=12
)
plt.tight_layout()
plt.savefig('ARD_vs_RF_importance_v31.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: ARD_vs_RF_importance_v31.png')

"""## 11. Temporal Holdout Validation

Fit on 2019-2022, predict 2023. Two things get reported:

**Error metrics** — how close the point predictions are.
**95% credible-interval coverage** — what fraction of held-out observations
fall inside the model's own uncertainty bounds.

These can diverge, and the divergence is informative. Coverage near 95% with
poor RMSE means the uncertainty quantification is honest even where the means
are imprecise — a reportable result, and the difference between "bounds we
computed" and "bounds we validated".
"""

# ════════════════════════════════════════════════════════════════════════════
# CELL 11: TEMPORAL HOLDOUT — fit 2019-2022, predict 2023
# ════════════════════════════════════════════════════════════════════════════

def temporal_holdout(data, target_col, rf_selected, holdout_year=2023):
    train = data[data['year'] < holdout_year]
    test  = data[data['year'] == holdout_year]

    model = build_global_gpr(train, target_col, rf_selected, verbose=False)

    # Build test matrix with the SAME columns in the SAME order
    d = test.copy()
    trt_dummies = pd.get_dummies(d['treatment_code'], prefix='trt').astype(float)
    d = pd.concat([d, trt_dummies], axis=1)
    for c in model['trt_cols']:
        if c not in d.columns:
            d[c] = 0.0

    sub = d[model['feats'] + [target_col]].dropna()
    if len(sub) == 0:
        return None

    X_test = (sub[model['feats']].values.astype(float) - model['X_mean']) / model['X_std']
    y_true = sub[target_col].values

    log_mean, log_std = model['gpr'].predict(X_test, return_std=True)
    y_pred  = np.expm1(log_mean)
    y_lo    = np.clip(np.expm1(log_mean - 1.96 * log_std), 0, None)
    y_hi    = np.expm1(log_mean + 1.96 * log_std)

    resid = y_true - y_pred
    rmse  = np.sqrt(np.mean(resid ** 2))
    mae   = np.mean(np.abs(resid))
    bias  = np.mean(resid)
    ss_res = np.sum(resid ** 2)
    ss_tot = np.sum((y_true - y_true.mean()) ** 2)
    r2 = 1 - ss_res / ss_tot if ss_tot > 0 else np.nan
    coverage = np.mean((y_true >= y_lo) & (y_true <= y_hi))
    mean_width = np.mean(y_hi - y_lo)

    return {
        'n_train': model['n'], 'n_test': len(sub),
        'y_true': y_true, 'y_pred': y_pred, 'y_lo': y_lo, 'y_hi': y_hi,
        'rmse': rmse, 'mae': mae, 'bias': bias, 'r2': r2,
        'coverage': coverage, 'mean_ci_width': mean_width,
    }


holdout = {}
for target, model in global_models.items():
    label = model['label']
    res = temporal_holdout(gpr_input, target, top_features[target])
    holdout[target] = res
    if res is None:
        print(f'{label}: no usable holdout rows')
        continue
    print(f'\n=== {label} — temporal holdout (train 2019-2022, test 2023) ===')
    print(f'  n train / test      : {res["n_train"]} / {res["n_test"]}')
    print(f'  RMSE                : {res["rmse"]:.2f} mg/kg')
    print(f'  MAE                 : {res["mae"]:.2f} mg/kg')
    print(f'  Bias (pred - obs)   : {-res["bias"]:+.2f} mg/kg')
    print(f'  R2                  : {res["r2"]:.3f}')
    print(f'  95% CI coverage     : {res["coverage"]*100:.1f}%  (target 95%)')
    print(f'  Mean CI width       : {res["mean_ci_width"]:.1f} mg/kg')

# ── Observed vs predicted, with CI bars ─────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
for ax, (target, res) in zip(axes, holdout.items()):
    if res is None:
        continue
    label = global_models[target]['label']
    inside = (res['y_true'] >= res['y_lo']) & (res['y_true'] <= res['y_hi'])

    ax.errorbar(res['y_true'][inside], res['y_pred'][inside],
                yerr=[res['y_pred'][inside] - res['y_lo'][inside],
                      res['y_hi'][inside] - res['y_pred'][inside]],
                fmt='o', ms=5, color='#1D9E75', ecolor='#9FE1CB',
                elinewidth=1, capsize=0, label='Inside 95% CI', zorder=3)
    if (~inside).any():
        ax.errorbar(res['y_true'][~inside], res['y_pred'][~inside],
                    yerr=[res['y_pred'][~inside] - res['y_lo'][~inside],
                          res['y_hi'][~inside] - res['y_pred'][~inside]],
                    fmt='o', ms=5, color='#E24B4A', ecolor='#F09595',
                    elinewidth=1, capsize=0, label='Outside 95% CI', zorder=3)

    lim = [0, max(res['y_true'].max(), res['y_hi'].max()) * 1.05]
    ax.plot(lim, lim, '--', color='gray', lw=1, zorder=1)
    ax.set_xlim(lim); ax.set_ylim(lim)
    ax.set_xlabel('Observed 2023 (mg/kg)')
    ax.set_ylabel('Predicted (mg/kg)')
    ax.set_title(f'{label}\nRMSE {res["rmse"]:.1f} | R2 {res["r2"]:.2f} | '
                 f'coverage {res["coverage"]*100:.0f}%', fontsize=10)
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

plt.suptitle('Temporal holdout: trained 2019-2022, tested on 2023',
             fontweight='bold', fontsize=12)
plt.tight_layout()
plt.savefig('temporal_holdout_v31.png', dpi=150, bbox_inches='tight')
plt.show()
print('Saved: temporal_holdout_v31.png')

# ════════════════════════════════════════════════════════════════════════════
# POSTER PANEL 4 — temporal holdout, poster style, 300 dpi PNG + SVG
# Run AFTER Cell 11 (needs the `holdout` dict in memory).
# ════════════════════════════════════════════════════════════════════════════
import matplotlib as mpl, matplotlib.pyplot as plt, numpy as np, os, urllib.request
from matplotlib import font_manager as fm

# fetch IBM Plex Sans so the panel matches the rest of the poster
os.makedirs('fonts', exist_ok=True)
for w in ['Regular', 'SemiBold']:
    p = f'fonts/IBMPlexSans-{w}.ttf'
    if not os.path.exists(p):
        urllib.request.urlretrieve(
            f'https://raw.githubusercontent.com/IBM/plex/master/packages/plex-sans/fonts/complete/ttf/IBMPlexSans-{w}.ttf', p)
    fm.fontManager.addfont(p)

mpl.rcParams.update({'font.family': ['IBM Plex Sans', 'DejaVu Sans'],
                     'svg.fonttype': 'none', 'font.size': 22})
INK, MUTED = '#14140F', '#57564F'
TEAL, TEAL_LIGHT, RED, RED_LIGHT = '#0F6E56', '#9FE1CB', '#A32D2D', '#F09595'

fig, axes = plt.subplots(1, 2, figsize=(13, 7))
for ax, (target, label) in zip(axes, [('nh4_mean', 'NH₄⁺'), ('no3_mean', 'NO₃⁻')]):
    r = holdout[target]
    inside = (r['y_true'] >= r['y_lo']) & (r['y_true'] <= r['y_hi'])
    for mask, c, cl in [(inside, TEAL, TEAL_LIGHT), (~inside, RED, RED_LIGHT)]:
        if mask.any():
            ax.errorbar(r['y_true'][mask], r['y_pred'][mask],
                        yerr=[r['y_pred'][mask] - r['y_lo'][mask],
                              r['y_hi'][mask] - r['y_pred'][mask]],
                        fmt='o', ms=7, color=c, ecolor=cl, elinewidth=1.4,
                        capsize=0, zorder=3)
    lim = [0, max(r['y_true'].max(), r['y_hi'].max()) * 1.04]
    ax.plot(lim, lim, '--', color='#8A887F', lw=1.5, zorder=1)
    ax.text(lim[1] * 0.97, lim[1] * 0.91, '1:1', ha='right', fontsize=13, color=MUTED)
    ax.set_xlim(lim); ax.set_ylim(lim)
    ax.set_xlabel('Observed 2023 (mg kg⁻¹)', fontsize=22)
    ax.set_ylabel('Predicted (mg kg⁻¹)', fontsize=22)
    ax.set_title(f'{label} Prediction',
                 fontsize=22, fontweight='semibold', loc='center', color=INK)
    for s in ['top', 'right']: ax.spines[s].set_visible(False)
    ax.grid(alpha=0.22)

plt.tight_layout()
for ext in ['png', 'svg']:
    fig.savefig(f'panel4_holdout.{ext}', dpi=300, transparent=True,
                bbox_inches='tight', pad_inches=0.15)
plt.show()
print('Saved panel4_holdout.png / .svg — download from the Colab file browser')

"""## 12. Projection Plots — 2019 to 2028

Trajectories now come from ONE model queried at different treatment / grazing
/ depth settings, so the separation between lines is a modelled contrast
rather than an artifact of fitting different subsets.

Forecast-year assumptions, stated explicitly because they determine the shape
of everything past 2023:
- SPEI held at the **observed mean** (roughly -0.6). v3.0 used 0.0, which
  implied conditions wetter than seven of the nine observed windows.
- GHG covariates held at their 2023 means.
- NDVI / EVI / SAR held at training means.
- Treatments assumed to continue unchanged.
"""

TREATMENTS   = [1, 2, 3]
GRAZING_VALS = [('No', '-', 'Not Grazed'), ('Yes', '--', 'Grazed')]

# ════════════════════════════════════════════════════════════════════════════
# CELL 12: PROJECTION FROM THE GLOBAL MODEL
# ════════════════════════════════════════════════════════════════════════════

FORECAST_START = 2024
YEARS_PRED = np.arange(2019, 2029)


def predict_trajectory(model, data, treatment_code, grazing, depth_cm):
    """Query the global model across years at one experimental setting."""
    depth_num = {'0-10': 5, '10-20': 15}[depth_cm]
    graz_bin  = 1 if grazing == 'Yes' else 0

    ctx = data[(data['treatment_code'] == treatment_code) &
               (data['grazing'] == grazing) &
               (data['depth_cm'] == depth_cm)]
    if len(ctx) == 0:
        return None

    rows = []
    for yr in YEARS_PRED:
        row = {}
        for f in model['continuous']:
            if f == 'year':
                row[f] = float(yr)
            elif yr >= FORECAST_START:
                if f == 'spei':
                    row[f] = data['spei'].mean()          # observed mean
                elif f in ('co2_mean', 'ch4_mean', 'n2o_mean'):
                    v = ctx.loc[ctx['year'] == 2023, f].mean()
                    row[f] = v if not np.isnan(v) else ctx[f].mean()
                else:
                    row[f] = ctx[f].mean()
            else:
                v = ctx.loc[ctx['year'] == yr, f].mean()
                row[f] = v if not np.isnan(v) else ctx[f].mean()
        for c in model['trt_cols']:
            row[c] = 1.0 if c == f'trt_{treatment_code}' else 0.0
        row['grazing_binary'] = float(graz_bin)
        row['depth_numeric']  = float(depth_num)
        rows.append(row)

    X = pd.DataFrame(rows)[model['feats']].values.astype(float)
    if np.isnan(X).any():
        return None
    Xn = (X - model['X_mean']) / model['X_std']

    log_mean, log_std = model['gpr'].predict(Xn, return_std=True)
    return {
        'years':   YEARS_PRED,
        'mean':    np.expm1(log_mean),
        'lower':   np.clip(np.expm1(log_mean - 1.96 * log_std), 0, None),
        'upper':   np.expm1(log_mean + 1.96 * log_std),
        'obs_x':   ctx['year'].values,
        'obs_y':   ctx[model['target']].values,
    }


def plot_global_projection(depth_cm='0-10', show_ci=True):
    for target, model in global_models.items():
        label = model['label']
        fig, axes = plt.subplots(1, 3, figsize=(17, 5), sharey=True)

        for ax, trt in zip(axes, TREATMENTS):
            color = COLORS[trt]
            for grazing_val, ls, graz_label in GRAZING_VALS:
                res = predict_trajectory(model, gpr_input, trt,
                                         grazing_val, depth_cm)
                if res is None:
                    continue
                if show_ci:
                    ax.fill_between(res['years'], res['lower'], res['upper'],
                                    alpha=0.10 if grazing_val == 'No' else 0.06,
                                    color=color)
                ax.plot(res['years'], res['mean'], color=color,
                        linestyle=ls, lw=2, label=f'GPR ({graz_label})')
                ax.scatter(res['obs_x'], res['obs_y'], color=color, s=36,
                           marker='o' if grazing_val == 'No' else '^',
                           edgecolors='white', linewidths=0.5, zorder=5,
                           label=f'Obs ({graz_label})')

            ax.axvline(2023.5, color='gray', linestyle=':', lw=1, alpha=0.7)
            ax.text(2023.7, ax.get_ylim()[1] * 0.93, 'Projection\u2192',
                    fontsize=7, color='gray')
            ax.set_title(TREATMENT_LABELS[trt], fontsize=10, fontweight='bold')
            ax.set_xlabel('Year')
            ax.set_xlim(2018.5, 2028.5)
            ax.set_ylim(bottom=0)
            ax.grid(alpha=0.3)
            ax.legend(fontsize=7)

        axes[0].set_ylabel(f'{label} (mg/kg)')
        plt.suptitle(
            f'{label} by treatment & grazing ({depth_cm} cm) — global GPR, v3.1\n'
            f'Projection under stated assumptions; no validated predictive skill',
            fontweight='bold', fontsize=11
        )
        plt.tight_layout()
        clean = label.replace('\u207a', '+').replace('\u207b', '-')
        fname = f'GPR_v31_global_{clean}_{depth_cm.replace("-", "_")}cm.png'
        plt.savefig(fname, dpi=150, bbox_inches='tight')
        plt.show()
        print(f'Saved: {fname}')


plot_global_projection('0-10')
plot_global_projection('10-20')

"""## 13. Export Forecast Table"""

# ════════════════════════════════════════════════════════════════════════════
# CELL 13: EXPORT FORECAST TABLE (from global model)
# ════════════════════════════════════════════════════════════════════════════

forecast_records = []
for target, model in global_models.items():
    var_label = 'NH4' if target == 'nh4_mean' else 'NO3'
    for trt in TREATMENTS:
        for depth in ['0-10', '10-20']:
            for grazing_val, _, _ in GRAZING_VALS:
                res = predict_trajectory(model, gpr_input, trt,
                                         grazing_val, depth)
                if res is None:
                    continue
                for yr, m, lo, hi in zip(res['years'], res['mean'],
                                         res['lower'], res['upper']):
                    forecast_records.append({
                        'variable':       var_label,
                        'treatment_code': trt,
                        'treatment_name': TREATMENT_LABELS[trt],
                        'depth_cm':       depth,
                        'grazing':        grazing_val,
                        'year':           int(yr),
                        'gpr_mean':       round(float(m), 3),
                        'ci_lower':       round(float(lo), 3),
                        'ci_upper':       round(float(hi), 3),
                        'period':         'observed' if yr <= 2023 else 'projection',
                        'model_version':  'v3.1_global',
                    })

forecast_df = pd.DataFrame(forecast_records)

# ── EDIT THIS PATH ──────────────────────────────────────────────────────────
EXPORT_PATH = '/content/drive/MyDrive/ENREEC/GHG/GPR_v3-1_forecast_table.csv'
# ────────────────────────────────────────────────────────────────────────────
forecast_df.to_csv(EXPORT_PATH, index=False)
print(f'Exported {forecast_df.shape[0]} rows to {EXPORT_PATH}')
forecast_df.head(10)

"""## 14. Validation Summary

One table to read before writing anything on the poster — it sorts each claim
by how much evidence stands behind it.
"""

# ════════════════════════════════════════════════════════════════════════════
# CELL 14: VALIDATION SUMMARY
# ════════════════════════════════════════════════════════════════════════════

print('=' * 72)
print('MODEL VALIDATION SUMMARY — v3.1')
print('=' * 72)

for target, model in global_models.items():
    label = model['label']
    h = holdout[target]
    ard = ard_relevance(model)
    rf  = results[target]['importances']
    cv  = results[target]['cv_scores']

    print(f'\n{label}')
    print(f'  Global GPR n            : {model["n"]} rows, {len(model["feats"])} dims')
    print(f'  RF leave-one-year-out R2: {cv.mean():.3f}  (per fold {cv.round(2)})')
    if h:
        print(f'  Holdout 2023 RMSE       : {h["rmse"]:.2f} mg/kg')
        print(f'  Holdout 2023 R2         : {h["r2"]:.3f}')
        print(f'  95% CI coverage         : {h["coverage"]*100:.1f}%')
    print(f'  Top ARD (GPR)           : {", ".join(ard.head(3).index)}')
    print(f'  Top MDI (RF)            : {", ".join(rf.head(3).index)}')

    shared = [f for f in rf.index if f in ard.index]
    agree  = [f for f in shared
              if f in ard.head(4).index and f in rf.head(4).index]
    print(f'  Agreed top-4 (both)     : {agree if agree else "none"}')

print('\n' + '=' * 72)
print('Read the agreement row first: covariates ranked highly by BOTH an')
print('impurity-based and a length-scale-based method are tier 1 claims.')
print('=' * 72)

"""## 15. Grazed vs Non-Grazed Statistical Comparison"""

print('=== Grazed vs Non-Grazed: Mann-Whitney U Test ===')
print('(Non-parametric — appropriate given non-normal N distributions)\n')

summary_records = []
for target, label in [('nh4_mg_kg','NH\u2084\u207a'), ('no3_mg_kg','NO\u2083\u207b')]:
    print(f'--- {label} ---')
    for trt in TREATMENTS:
        for year in sorted(df['year'].unique()):
            sub = df[(df['treatment_code']==trt) & (df['year']==year)]
            grazed     = sub[sub['grazing']=='Yes'][target].dropna()
            not_grazed = sub[sub['grazing']=='No'][target].dropna()
            if len(grazed) < 3 or len(not_grazed) < 3:
                continue
            stat, p = stats.mannwhitneyu(grazed, not_grazed, alternative='two-sided')
            sig = '***' if p<0.001 else '**' if p<0.01 else '*' if p<0.05 else 'ns'
            summary_records.append({
                'variable':        label,
                'treatment':       TREATMENT_LABELS[trt],
                'year':            year,
                'mean_grazed':     round(grazed.mean(), 2),
                'mean_not_grazed': round(not_grazed.mean(), 2),
                'diff':            round(grazed.mean() - not_grazed.mean(), 2),
                'p_value':         round(p, 4),
                'significance':    sig
            })
            print(f'  Trt {trt} | {year}: G={grazed.mean():.1f} '
                  f'NG={not_grazed.mean():.1f} '
                  f'diff={grazed.mean()-not_grazed.mean():+.1f} '
                  f'p={p:.4f} {sig}')

stats_df = pd.DataFrame(summary_records)

# Heatmap
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
for ax, var in zip(axes, ['NH\u2084\u207a','NO\u2083\u207b']):
    sub = stats_df[stats_df['variable']==var].pivot(
        index='treatment', columns='year', values='diff')
    p_sub = stats_df[stats_df['variable']==var].pivot(
        index='treatment', columns='year', values='p_value')
    sns.heatmap(sub, ax=ax, cmap='RdBu_r', center=0,
                annot=True, fmt='.1f', linewidths=0.5,
                cbar_kws={'label': 'Mean diff (G - NG)'})
    for i, trt in enumerate(sub.index):
        for j, yr in enumerate(sub.columns):
            try:
                p_val = p_sub.loc[trt, yr]
                sig = '***' if p_val<0.001 else '**' if p_val<0.01 else '*' if p_val<0.05 else ''
                if sig:
                    ax.text(j+0.5, i+0.8, sig, ha='center', fontsize=10)
            except:
                pass
    ax.set_title(f'{var} — Grazed minus Not Grazed (mg/kg)\n'
                 f'* p<0.05  ** p<0.01  *** p<0.001')
    ax.set_xlabel('Year')
    ax.set_ylabel('Treatment')

plt.suptitle('Grazing Effect on Soil N by Treatment and Year', fontweight='bold')
plt.tight_layout()
plt.savefig('grazing_effect_heatmap_v3.png', dpi=150, bbox_inches='tight')
plt.show()

# Export stats table
STATS_PATH = '/content/drive/MyDrive/ENREEC/GHG//grazing_stats_v3.csv'
stats_df.to_csv(STATS_PATH, index=False)
print(f'\nStats table saved to: {STATS_PATH}')

"""## 16. Tableau Export"""

# ════════════════════════════════════════════════════════════════════════════
# TABLEAU EXPORT CELL
# ════════════════════════════════════════════════════════════════════════════

TABLEAU_DIR = '/content/drive/MyDrive/ENREEC/Tableau'

PLOT_COORDS = {
    101: {'lat': 41.16802171432988, 'lon': -96.43858599666265,
          'treatment_code': 2, 'treatment_name': 'Fertilized Triticale'},
    102: {'lat': 41.16802314205589, 'lon': -96.43825409190654,
          'treatment_code': 1, 'treatment_name': 'Unfertilized Triticale'},
    103: {'lat': 41.16801885887779, 'lon': -96.43794684293230,
          'treatment_code': 3, 'treatment_name': 'Triticale w/ Legume'},
    201: {'lat': 41.16818733033986, 'lon': -96.43858599666265,
          'treatment_code': 3, 'treatment_name': 'Triticale w/ Legume'},
    202: {'lat': 41.16818161944992, 'lon': -96.43819529734974,
          'treatment_code': 1, 'treatment_name': 'Unfertilized Triticale'},
    203: {'lat': 41.16819161350698, 'lon': -96.43794684293230,
          'treatment_code': 2, 'treatment_name': 'Fertilized Triticale'},
    301: {'lat': 41.16840577150589, 'lon': -96.43851771911282,
          'treatment_code': 2, 'treatment_name': 'Fertilized Triticale'},
    302: {'lat': 41.16841291009379, 'lon': -96.43822564292745,
          'treatment_code': 1, 'treatment_name': 'Unfertilized Triticale'},
    303: {'lat': 41.16841291009379, 'lon': -96.43793735993927,
          'treatment_code': 3, 'treatment_name': 'Triticale w/ Legume'},
}

plot_df = pd.DataFrame([
    {'plot_id': k, 'lat': v['lat'], 'lon': v['lon'],
     'treatment_code': v['treatment_code'],
     'treatment_name': v['treatment_name']}
    for k, v in PLOT_COORDS.items()
])

# ── File 1: Plot master ─────────────────────────────────────────────────────
plot_df.to_csv(f'{TABLEAU_DIR}/tableau_plot_master.csv', index=False)
print('Saved: tableau_plot_master.csv')

# ── File 2: Observed N, plot-level, with SPEI attached ──────────────────────
obs_cols = ['plot_id','year','time_point','depth_cm','grazing',
            'treatment_code','treatment_label','nh4_mean','no3_mean','spei']
obs_n = (gpr_input[obs_cols]
         .rename(columns={'treatment_label': 'treatment_name'})
         .merge(plot_df[['plot_id','lat','lon']], on='plot_id', how='left'))
obs_n.to_csv(f'{TABLEAU_DIR}/tableau_observed_N.csv', index=False)
print(f'Saved: tableau_observed_N.csv ({len(obs_n)} rows)')

# ── File 3: GPR forecast broadcast to plot coordinates ──────────────────────
# forecast_df is treatment-level; every plot under a treatment gets the SAME
# values. Use File 5 for an honest treatment-resolution map.
if 'treatment_code' not in forecast_df.columns:
    raise ValueError(f"forecast_df lacks treatment_code. Has: {forecast_df.columns.tolist()}")

forecast_tableau = forecast_df.merge(
    plot_df[['plot_id','lat','lon','treatment_code']],
    on='treatment_code', how='left'
)
if forecast_tableau['lat'].isna().any():
    print('WARNING: unmatched treatment_code:',
          forecast_tableau.loc[forecast_tableau['lat'].isna(),
                               'treatment_code'].unique())
forecast_tableau.to_csv(f'{TABLEAU_DIR}/tableau_gpr_forecast.csv', index=False)
print(f'Saved: tableau_gpr_forecast.csv ({len(forecast_df)} -> {len(forecast_tableau)} rows)')

# ── File 4: RF importance ───────────────────────────────────────────────────
# reindex() on RF_FEATURES is required — results[...]['importances'] is sorted
# descending and the two targets sort differently, so .values would misalign.
rf_importance = pd.DataFrame({
    'feature':        [FEATURE_LABELS.get(f, f) for f in RF_FEATURES],
    'importance_nh4': results['nh4_mean']['importances'].reindex(RF_FEATURES).values,
    'importance_no3': results['no3_mean']['importances'].reindex(RF_FEATURES).values,
})
rf_importance.to_csv(f'{TABLEAU_DIR}/tableau_rf_importance.csv', index=False)
print('Saved: tableau_rf_importance.csv')
print(rf_importance.round(4).to_string(index=False))

# ── File 5: Treatment centroids for the forecast map ────────────────────────
treatment_centroids = plot_df.groupby('treatment_code', as_index=False).agg(
    lat=('lat','mean'), lon=('lon','mean')
)
forecast_centroids = forecast_df.merge(treatment_centroids,
                                       on='treatment_code', how='left')
forecast_centroids.to_csv(f'{TABLEAU_DIR}/tableau_forecast_centroids.csv',
                          index=False)
print(f'Saved: tableau_forecast_centroids.csv ({len(forecast_centroids)} rows)')

# ── File 6: SPEI per sampling window (GEE-extracted) ────────────────────────
# Uses spei_df from Cell 4b. Do NOT reassign spei_df here — Cell 7 merges it.
spei_export = spei_df.copy()
spei_export['spei_model'] = spei_export[SPEI_CHOICE]
spei_export.to_csv(f'{TABLEAU_DIR}/tableau_spei.csv', index=False)
print('Saved: tableau_spei.csv')
print(spei_export.round(3).to_string(index=False))

print('\nAll six Tableau export files ready.')

# ── Verify exports ──────────────────────────────────────────────────────────
print('forecast_centroids columns:')
print(forecast_centroids.columns.tolist())

dupes = [c for c in forecast_centroids.columns if c.endswith(('_x', '_y'))]
print('Duplicate-merge columns:', dupes if dupes else 'none')

print('\nforecast_tableau columns:')
print(forecast_tableau.columns.tolist())

print('\nobs_n columns:')
print(obs_n.columns.tolist())
print('SPEI values present:', obs_n['spei'].notna().sum(), '/', len(obs_n))

"""## New Aggregated Tableau Dashboard for v3.1"""

# ════════════════════════════════════════════════════════════════════════════
# DASHBOARD EXPORT — aggregated results only, no individual sample values
# Run at the end of the v3.1 notebook, after Cells 1–14 (needs df, results,
# perm_results, global_models, holdout, spei_df, PLOTS in memory).
# ════════════════════════════════════════════════════════════════════════════
import os
import numpy as np
import pandas as pd
from scipy import stats

# ── EDIT THIS PATH ──────────────────────────────────────────────────────────
OUT = '/content/drive/MyDrive/ENREEC/Tableau/Aggregated v3.1'
# ────────────────────────────────────────────────────────────────────────────
os.makedirs(OUT, exist_ok=True)

ANALYTES = {'nh4_mg_kg': 'NH4', 'no3_mg_kg': 'NO3'}
TRT = {1: 'Unfertilized', 2: 'Fertilized', 3: 'Legume'}
MIN_N = 3   # groups smaller than this are dropped so no mean is a single sample


def save(frame, name):
    frame.to_csv(f'{OUT}/{name}.csv', index=False)
    print(f'{name:26s} {len(frame):4d} rows')


# 1 · Coverage audit — one row per variable × year
COVERAGE = {
    'NH4 / NO3':        ['Complete'] * 5,
    'GHG flux':         ['Not collected', 'All treatments', 'All treatments', 'All treatments', 'All treatments'],
    'pH / EC / BD':     ['All treatments', 'Plot IDs lost', 'Not collected', 'Time 2 only', 'Time 2 only'],
    'Carbon fractions': ['Not collected', 'Not collected', 'Not collected', 'Time 2 only', 'Time 2 only'],
    'FAME':             ['All treatments', 'Not collected', 'Not collected', 'Time 2 only', 'Time 2 only'],
}
ROLE = {'NH4 / NO3': 'Response', 'GHG flux': 'Covariate', 'pH / EC / BD': 'Baseline',
        'Carbon fractions': 'Snapshot', 'FAME': 'Snapshot'}
cov = pd.DataFrame([(v, y, s) for v, row in COVERAGE.items()
                    for y, s in zip(range(2019, 2024), row)],
                   columns=['variable', 'year', 'status'])
cov['role'] = cov['variable'].map(ROLE)
save(cov, 'dash_coverage')

# 2 · Nitrogen means — treatment × grazing × depth × year × time point
long = (df.melt(id_vars=['year', 'time_point', 'treatment_code', 'grazing', 'depth_cm'],
                value_vars=list(ANALYTES), var_name='analyte', value_name='value')
          .dropna(subset=['value']))
means = (long.groupby(['analyte', 'treatment_code', 'grazing', 'depth_cm', 'year', 'time_point'])['value']
             .agg(mean='mean', sd='std', n='count').reset_index())
means = means[means['n'] >= MIN_N].copy()
means['analyte'] = means['analyte'].map(ANALYTES)
means['treatment'] = means['treatment_code'].map(TRT)
save(means.drop(columns='treatment_code').round(3), 'dash_n_means')

# 3 · Covariate relevance — three methods × two analytes, long format
NAMES = dict(FEATURE_LABELS, trt_1='Treatment: Unfertilized',
             trt_2='Treatment: Fertilized', trt_3='Treatment: Legume')
rows = []
for target, a in [('nh4_mean', 'NH4'), ('no3_mean', 'NO3')]:
    for c, v in results[target]['importances'].items():
        rows.append((a, 'RF impurity', c, v))
    for c, v in perm_results[target]['raw'].items():
        rows.append((a, 'Permutation (change in MSE)', c, v))
    for c, v in ard_relevance(global_models[target]).items():
        rows.append((a, 'GPR ARD', c, v))
rel = pd.DataFrame(rows, columns=['analyte', 'method', 'covariate', 'value'])
rel['covariate'] = rel['covariate'].map(lambda c: NAMES.get(c, c))
rel['rank'] = (rel.groupby(['analyte', 'method'])['value']
                  .rank(ascending=False, method='min').astype(int))
save(rel.round(4), 'dash_relevance')

# 4 · Grazing effects — summary statistics with n, plus Holm correction
#     within the 2023 endpoint family (3 treatments × 2 analytes = 6 tests)
ge = []
for col, a in ANALYTES.items():
    for trt, tname in TRT.items():
        for yr in sorted(df['year'].unique()):
            sub = df[(df['treatment_code'] == trt) & (df['year'] == yr)]
            g = sub.loc[sub['grazing'] == 'Yes', col].dropna()
            ng = sub.loc[sub['grazing'] == 'No', col].dropna()
            if len(g) < MIN_N or len(ng) < MIN_N:
                continue
            p = stats.mannwhitneyu(g, ng, alternative='two-sided').pvalue
            ge.append(dict(analyte=a, treatment=tname, year=int(yr),
                           mean_grazed=g.mean(), sd_grazed=g.std(), n_grazed=len(g),
                           mean_ungrazed=ng.mean(), sd_ungrazed=ng.std(), n_ungrazed=len(ng),
                           diff=g.mean() - ng.mean(), p_value=p))
ge = pd.DataFrame(ge)
end = ge['year'] == 2023
pv = ge.loc[end, 'p_value'].to_numpy()
order, k, running = np.argsort(pv), len(pv), 0.0
holm = np.empty(k)
for i, idx in enumerate(order):
    running = max(running, min(1.0, (k - i) * pv[idx]))
    holm[idx] = running
ge['p_holm_2023'] = np.nan
ge.loc[end, 'p_holm_2023'] = holm
ge['sig_uncorrected'] = np.select([ge['p_value'] < 0.01, ge['p_value'] < 0.05], ['**', '*'], '')
save(ge.round(4), 'dash_grazing_effects')

# 5 · Water balance per sampling window (public GRIDMET data)
save(spei_df[['year', 'time_point'] + SPEI_BANDS].round(3), 'dash_spei')

# 6 · Temporal holdout — points are plot-level means, not samples
pts, met = [], []
for target, a in [('nh4_mean', 'NH4'), ('no3_mean', 'NO3')]:
    h = holdout[target]
    pts.append(pd.DataFrame(dict(analyte=a, observed=h['y_true'], predicted=h['y_pred'],
                                 lower95=h['y_lo'], upper95=h['y_hi'])))
    met.append(dict(analyte=a, n_train=h['n_train'], n_test=h['n_test'], rmse=h['rmse'],
                    mae=h['mae'], bias=h['bias'], r2=h['r2'], coverage95=h['coverage'],
                    mean_interval_width=h['mean_ci_width']))
pts = pd.concat(pts, ignore_index=True)
pts['inside95'] = (pts['observed'] >= pts['lower95']) & (pts['observed'] <= pts['upper95'])
save(pts.round(3), 'dash_holdout_points')
save(pd.DataFrame(met).round(3), 'dash_holdout_metrics')

# 7 · Plot layout for the field map (coordinates rounded to ~1 m)
save(pd.DataFrame([{'plot_id': pid, 'treatment': TRT[info['treatment']],
                    'lat': round(info['lat'], 5), 'lon': round(info['lon'], 5)}
                   for pid, info in PLOTS.items()]), 'dash_plots')

print(f'\nDone. {len(os.listdir(OUT))} files in {OUT}')
print(f'Nitrogen means and grazing statistics use groups of n >= {MIN_N}; '
      'no file contains individual sample values.')